INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Rat','enemy','Rat','Ratte','Ratte');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('FireRat','enemy','Fire Rat','Feuerratte','Füürratte');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Nekomata','enemy','Nekomata','Nekomata','Nekomata');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Crow','enemy','Crow','Krähe','Raab');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('SkeletonDefault','enemy','Skeleton','Skelett','Skelett');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('SkeletonArcher','enemy','Skeleton Archer','Skelettschütze','Skelett-Bögeler');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('SkeletonMage','enemy','Skeleton Mage','Skelettmagier','Skelett-Magier');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('SkeletonRogue','enemy','Skeleton Rogue','Skelettschurke','Skelett-Schuft');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('SkeletonWarrior','enemy','Skeleton Warrior','Skelettkrieger','Skelett-Chrieger');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('SkeletonShield','enemy','Shielded Skeleton','Schild-Skelett','Schild-Skelett');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Gargoyle','enemy','Gargoyle','Gargoyle','Gargoyle');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Hunter','enemy','Edmond','Edmond','Edmond');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Wisp','enemy','Wisp','Irrlicht','Irrliecht');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Seagull','enemy','Seagull','Möwe','Möwe');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Wolf','enemy','Wolf','Wolf','Wolf');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Cairn','enemy','Cairn Wraith','Cairn Geist','Cairn Geist');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('MysteriousBeast','enemy','Mysterious Beast','Mysteriöses Biest','Mysteriöses Biescht');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('CavernBeast','enemy','Cavern Beast','Höhlenmonster','Höhlemonster');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BossKhajag','enemy','Khajag, the Cavern Guardian','Khajag, Wächter der Höhlen','Khajag, Wächter vode Höhlene');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BossZeff','enemy','Zeff','Zeff','Zeff');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Book','enemy','Book','Buch','Buech');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Observer','enemy','Observer Spell','Beobachter-Zauber','Beobachter-Zauber');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Warden','enemy','Warden Spell','Wächter-Zauber','Wächter-Zauber');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Prisoner','enemy','Prisoner','Gefangener','Gfangene');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Ooze','enemy','Ooze','Schleim','Schleim');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Bat','enemy','Bat','Fledermaus','Flädermuus');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ElysiaFledgling','enemy','Elysia''s Fledgling','Elysia''s Küken','Bibeli vode Elysia');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BossElysia','enemy','Elysia, Envoy of the Storm','Elysia, Gesandte des Sturms','Elysia, Gsandti vom Sturm');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Elysia','enemy','Huge Bird','Riesiger Vogel','Riesige Vogel');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DragonWhelp','enemy','Dragon Whelp','Drachenwelpe','Drächeli');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BossElysia','enemy','Janus, Guardian of the Sewers','Janus, Wächter der Kanalisation','Janus, Wächter vode Kanalisation');