INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_edmond','npc','Edmond','Edmond','Edmond');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_ingrid','npc','Ingrid','Ingrid','Ingrid');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_rhendal','npc','Elder Rhendal','Ältester Rhendal','Älteste Rhendal');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_innkeeper','npc','Innkeeper','Wirt','Wirt');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_vincent','npc','Vincent','Vincent','Vincent');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_thea','npc','Thea','Thea','Thea');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_andrew','npc','Andrew','Andrew','Andrew');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_inina','npc','High Priestess Inina','Hohepriesterin Inina','Hohepriesterin Inina');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_paladin','npc','Paladin','Paladin','Paladin');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_sheep','npc','Sheep','Schaf','Schöfli');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_ivo','npc','Ivo','Ivo','Ivo');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_tristan','npc','Tristan','Tristan','Tristan');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_zeff','npc','Zeff','Zeff','Zeff');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_cityguard','npc','City Guard','Stadtwache','Stadtwach');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_steven','npc','Steven','Steven','Steven');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_harek','npc','Harek','Harek','Harek');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_edgar','npc','Overseer Edgar','Aufseher Edgar','Ufseher Edgar');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_leeroy','npc','Leeroy','Leeroy','Leeroy');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_yorick','npc','Skeleton','Skelett','Skelett');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_morris','npc','Morris','Morris','Morris');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_helena','npc','Helena','Helena','Helena');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_jonathan','npc','Jonathan','Jonathan','Jonathan');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_syrah','npc','Syrah','Syrah','Syrah');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_lloyd','npc','Commander Lloyd','Kommandant Lloyd','Kommandant Lloyd');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_morgiana','npc','Morgiana "The Butcher"','Morgiana "Die Metzgerin"','"Metzgerin" Morgiana');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_roy','npc','Roy "The Demon"','Roy "Der Dämon"','"Dämon" Roy');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_jeremy','npc','Jeremy "The Fox" Siek','Jeremy "Der Fuchs" Siek','Jeremy "De Fuchs" Siek');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_clementia','npc','Clementia','Clementia','Clementia');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_alonso','npc','Alonso','Alonso','Alonso');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_douglas','npc','Douglas','Douglas','Douglas');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_thiran','npc','Thiran','Thiran','Thiran');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_nuray','npc','Nuray','Nuray','Nuray');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_morton','npc','Grave Digger Morton','Totengräber Morton','Totegräber Morton');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_robert','npc','Robert','Robert','Robert');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_lua','npc','Lua','Lua','Lua');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_waldemar','npc','Waldemar','Waldemar','Waldemar');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_luiz','npc','Luiz','Luiz','Luiz');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_citizen','npc','Citizen','Bürger','Bürger');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_citizenf','npc','Citizen','Bürgerin','Bürgerin');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_jack','npc','Jack','Jack','Jack');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('npc_lee','npc','Lee','Lee','Lee','Sota');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('npc_luv','npc','Luv','Luv','Luv','Barlo');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_adelya','npc','Adelya','Adelya','Adelya');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_mona','npc','Mona','Mona','Mona');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_koray','npc','Koray','Koray','Koray');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_dondiego','npc','Don Diego','Don Diego','Don Diego');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_kia','npc','Kia','Kia','Kia');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_timo','npc','Timo','Timo','Timo');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_laslo','npc','Laslo','Laslo','Laslo');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_yasha','npc','Yasha','Yasha','Yasha');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_zephyra','npc','Zephyra','Zephyra','Zephyra');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_lola','npc','Lola','Lola','Lola');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_rana','npc','Rana','Rana','Rana');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_jason','npc','Jason','Jason','Jason');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_braham','npc','Braham Teawenth','Braham Teawenth','Braham Teawenth');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_patrappa','npc','Patrappa','Patrappa','Patrappa');