INSERT INTO text (text_id, english, german, swiss_german) values ('NoReputation','No one has ever heard of you.','Niemand hat je von dir gehört.','Niemert schert sich en Dreck um dich.');

INSERT INTO text (text_id, english, german, swiss_german) values ('necromancer','Necromancers','Nekromanten','Nekromante');
INSERT INTO text (text_id, english, german, swiss_german) values ('necromancer_25','You are unworthy in the eyes of the Necromancers','Du bist unwürdig in den Augen der Nekromanten.','Du bisch unwürdig ide Auge vode Nekromante.');
INSERT INTO text (text_id, english, german, swiss_german) values ('necromancer_50','You''ve caught the interest of the Necromancers.','Du hast das Interesse der Nekromanten geweckt.','Du hesch es Interesse vode Nekromante gweckt.');
INSERT INTO text (text_id, english, german, swiss_german) values ('necromancer_75','The Necromancers respect you.','Die Nekromanten respektieren dich.','D''Nekromante respektiered dich.');
INSERT INTO text (text_id, english, german, swiss_german) values ('necromancer_100','...','...','...');
INSERT INTO text (text_id, english, german, swiss_german) values ('thief','Guild of the Shadow Stalkers','Gilde der Schattenläufer','Gilde vode Schatteläufer');
INSERT INTO text (text_id, english, german, swiss_german) values ('thief_25','The guild doesn''t trust you.','Die Gilde vertraut dir nicht.','D''Gilde traut dir nid.');
INSERT INTO text (text_id, english, german, swiss_german) values ('thief_50','The guild accepts you.','Die Gilde akzeptiert dich.','D''Gilde akzeptiert dich.');
INSERT INTO text (text_id, english, german, swiss_german) values ('thief_75','You are considered a full member of the guild.','Du bist ein vollständiges Mitglied der Gilde.','Du bisch es vollständigs Mitglied vode Gilde.');
INSERT INTO text (text_id, english, german, swiss_german) values ('thief_100','You have grown irreplacable for the guild.','Du bist für die Gilde unersetzlich geworden.','Du bisch für d''Gilde unersetzlich worde.');
INSERT INTO text (text_id, english, german, swiss_german) values ('cleric','Clerics','Kleriker','Kleriker');
INSERT INTO text (text_id, english, german, swiss_german) values ('cleric_25','You don''t exist for the Clerics.','Du existierst nicht für die Kleriker.','Du existiersch nid fürd Kleriker.');
INSERT INTO text (text_id, english, german, swiss_german) values ('cleric_50','You are considered useful - but replacable.','Du wirst als nützlich angesehen - aber ersetzbar.','Si halted dich für nützlich - aber ersetzbar.');
INSERT INTO text (text_id, english, german, swiss_german) values ('cleric_75','The Clerics compliment you on accepting the way of the Eternal Light.','Die Kleriker loben, dass du den Weg des Ewigen Lichts eingeschlagen hast.','D''Kleriker lobeds, dass du de Weg vom Ewige Liecht iigschlage hesch.');
INSERT INTO text (text_id, english, german, swiss_german) values ('cleric_100','The Clerics only speak highly of you.','Die Kleriker sprechen nur in den höchsten Tönen von dir.','D''Kleriker reded nur ide höchste Tön vo dir.');
INSERT INTO text (text_id, english, german, swiss_german) values ('elementalist','Elementalists','Elementarmagier','Elementarmagier');
INSERT INTO text (text_id, english, german, swiss_german) values ('elementalist_25','You still have to prove yourself to the Elementalists.','Du musst dich den Elementarmagiern noch beweisen.','Du muesch dich de Elementarmagier no bewiise.');
INSERT INTO text (text_id, english, german, swiss_german) values ('elementalist_50','The Elementalists have hope in you.','Die Elementarmagier haben Hoffnung in dich.','D''Elementarmagier hend Hoffnig i dich.');
INSERT INTO text (text_id, english, german, swiss_german) values ('elementalist_75','You seem to be a worthy Elementalist.','Du scheinst ein würdiger Elementarmagier zu sein.','Du schiinsch en würdige Elementarmagier abz''gä.');
INSERT INTO text (text_id, english, german, swiss_german) values ('elementalist_100','You are a legend.','Du bist eine Legende.','Du bisch e Legende.');
INSERT INTO text (text_id, english, german, swiss_german) values ('druid','Druids','Druiden','Druide');
INSERT INTO text (text_id, english, german, swiss_german) values ('druid_25','The druids do not think that much of you.','Die Druiden halten nicht sonderlich viel von dir.','D''Druide halted nid sonderlich viel vo dir.');
INSERT INTO text (text_id, english, german, swiss_german) values ('druid_50','The druids appreciate your help.','Die Druiden schätzen deine Hilfe.','D''Druide schätzed dini Hilf.');
INSERT INTO text (text_id, english, german, swiss_german) values ('druid_75','...','...','...');
INSERT INTO text (text_id, english, german, swiss_german) values ('druid_100','...','...','...');