INSERT INTO text (text_id, english, german, swiss_german) values ('Active','Active','Aktiv','Aktiv');
INSERT INTO text (text_id, english, german, swiss_german) values ('AdditionalResistance','Additional Resistance','Zusätzlicher Widerstand','Zuesätzliche Widerstand');
INSERT INTO text (text_id, english, german, swiss_german) values ('AllowedModifiers','Allowed Gem Types','Erlaubte Edelsteintypen','Erlaubti Edelsteitype');
INSERT INTO text (text_id, english, german, swiss_german) values ('Apply','Apply','Anwenden','Awende');
INSERT INTO text (text_id, english, german, swiss_german) values ('And','and','und','und');
INSERT INTO text (text_id, english, german, swiss_german) values ('Armor','Armour','Rüstung','Rüschtig');
INSERT INTO text (text_id, english, german, swiss_german) values ('Back','Back','Zurück','Zrugg');
INSERT INTO text (text_id, english, german, swiss_german) values ('BackToCheckpoint','Back to checkpoint','Zurück zum Kontrollpunkt','Zrugg zum Checkpoint');
INSERT INTO text (text_id, english, german, swiss_german) values ('BackToMenu','Menu','Menu','Menu');
INSERT INTO text (text_id, english, german, swiss_german) values ('Book','Book','Buch','Buech');
INSERT INTO text (text_id, english, german, swiss_german) values ('Cancel','Cancel','Abbrechen','Abbreche');
INSERT INTO text (text_id, english, german, swiss_german) values ('CannotEquipInLevel','You cannot equip items inside a level!','Gegenstände können nicht in einem Level ausgerüstet werden!','Gegeständ chönd nid imne Level agleit werde!');
INSERT INTO text (text_id, english, german, swiss_german) values ('CannotConsumePermanentInLevel','You cannot consume permanent items inside a level!','Gegenstände mit permanenten Boni können nicht in einem Level verwendet werden!','Gegeständ mit permanente Boni chönd nid imne Level verbruucht werde!');
INSERT INTO text (text_id, english, german, swiss_german) values ('CannotConsumeItemInMap','You cannot consume food items on a map!','Verzehrbare Gegenstände können nicht auf einer Karte verwendet werden!','Ässbari Gegeständ chönd nid ufere Charte verbruucht werde!');
INSERT INTO text (text_id, english, german, swiss_german) values ('CharacterInfo','Character Info','Charakter Info','Charakter Info');
INSERT INTO text (text_id, english, german, swiss_german) values ('Checkpoint','Checkpoint','Kontrollpunkt','Checkpoint');
INSERT INTO text (text_id, english, german, swiss_german) values ('CheckpointReached','Checkpoint reached','Kontrollpunkt erreicht','Checkpoint erreicht');
INSERT INTO text (text_id, english, german, swiss_german) values ('Chest','Chest','Truhe','Chischte');
INSERT INTO text (text_id, english, german, swiss_german) values ('Chop','Chop','Hauen','Haue');
INSERT INTO text (text_id, english, german, swiss_german) values ('ClickToTeleport','Click to teleport','Klicken zum Teleportieren','Klicke zum Teleportiere');
INSERT INTO text (text_id, english, german, swiss_german) values ('Completed','Completed','Fertig','Fertig');
INSERT INTO text (text_id, english, german, swiss_german) values ('ConfigurationSaved','Configuration was saved.','Einstellungen wurden erfolgreich gespeichert. ','Iistellige sind erfolgriich gspeicheret.');
INSERT INTO text (text_id, english, german, swiss_german) values ('Confirm','Confirm','Bestätigen','Bestätige');
INSERT INTO text (text_id, english, german, swiss_german) values ('Consumables','Consumables','Tränke und Nahrung','Tränk und Ässe');
INSERT INTO text (text_id, english, german, swiss_german) values ('Consumed','consumed:','verbraucht:','verbruucht:');
INSERT INTO text (text_id, english, german, swiss_german) values ('Cooldown','Cooldown','Abklingzeit','Abklingziit');
INSERT INTO text (text_id, english, german, swiss_german) values ('CooldownReduction','Cooldown Reduction','Abklingzeitverringerung','Abklingziitverringering');
INSERT INTO text (text_id, english, german, swiss_german) values ('Count','Count','Anzahl','Aazahl');
INSERT INTO text (text_id, english, german, swiss_german) values ('Credits','Credits','Mitwirkende','Credits');
INSERT INTO text (text_id, english, german, swiss_german) values ('Critical','Critical','Kritisch','Kritisch');
INSERT INTO text (text_id, english, german, swiss_german) values ('CriticalHitChance','Critical Hit Chance','Kritische Trefferchance','Kritischi Trefferchance');
INSERT INTO text (text_id, english, german, swiss_german) values ('Damage','Damage','Schaden','Schade');
INSERT INTO text (text_id, english, german, swiss_german) values ('DamageType','Damage Type','Schadenstyp','Schadetyp');
INSERT INTO text (text_id, english, german, swiss_german) values ('DamagePerSecond','Damage per Second','Schaden pro Sekunde','Schade pro Sekunde');
INSERT INTO text (text_id, english, german, swiss_german) values ('Default','Default','Standardwert','Standardwert');
INSERT INTO text (text_id, english, german, swiss_german) values ('Delete','Delete','Löschen','Lösche');
INSERT INTO text (text_id, english, german, swiss_german) values ('DisplayMode','Display Mode','Anzeigemodus','Aazeigemodus');
INSERT INTO text (text_id, english, german, swiss_german) values ('DialogueEnd','[END]','[ENDE]','[FERTIG]');
INSERT INTO text (text_id, english, german, swiss_german) values ('DialogueTrade','[TRADE]','[HANDELN]','[HANDLE]');
INSERT INTO text (text_id, english, german, swiss_german) values ('DisplayDamageNumbers','Display Damage Numbers','Schadensszahlen anzeigen','Schadensszahle aazeige');
INSERT INTO text (text_id, english, german, swiss_german) values ('DisplayHints','Display Hints','Tipps anzeigen','Tipps aazeige');
INSERT INTO text (text_id, english, german, swiss_german) values ('Divine','Divine','Heilig','Heilig');
INSERT INTO text (text_id, english, german, swiss_german) values ('Documents','Documents','Schriftstücke','Dokument');
INSERT INTO text (text_id, english, german, swiss_german) values ('Done','Done','Erfüllt','Erfüllt');
INSERT INTO text (text_id, english, german, swiss_german) values ('Door','Door','Tür','Türe');
INSERT INTO text (text_id, english, german, swiss_german) values ('Duration','Duration','Dauer','Duur');
INSERT INTO text (text_id, english, german, swiss_german) values ('Elemental','Elemental','Elementar','Elementar');
INSERT INTO text (text_id, english, german, swiss_german) values ('English','English','Englisch','Englisch');
INSERT INTO text (text_id, english, german, swiss_german) values ('EqBack','Back','Rücken','Rugge');
INSERT INTO text (text_id, english, german, swiss_german) values ('EqBody','Chest','Brust','Bruscht');
INSERT INTO text (text_id, english, german, swiss_german) values ('EqHead','Head','Kopf','Chopf');
INSERT INTO text (text_id, english, german, swiss_german) values ('EqNeck','Neck','Hals','Hals');
INSERT INTO text (text_id, english, german, swiss_german) values ('EqRing','Finger','Finger','Finger');
INSERT INTO text (text_id, english, german, swiss_german) values ('EqWeapon','Weapon','Waffe','Waffe');
INSERT INTO text (text_id, english, german, swiss_german) values ('Equipment','Equipment','Ausrüstung','Usrüschtig');
INSERT INTO text (text_id, english, german, swiss_german) values ('EquipWeapon','Equip a weapon with spell slots to use spells.','Rüste eine Waffe mit Zauber-Slots aus, um Zauber einzusetzen.','Leg e Waffe mit Zauber-Slots ah zum Zauber iisetze.');
INSERT INTO text (text_id, english, german, swiss_german) values ('Empty','Empty','Leer','Läär');
INSERT INTO text (text_id, english, german, swiss_german) values ('EmptySlot','Empty slot','Leerer Platz','Lääre Platz');
INSERT INTO text (text_id, english, german, swiss_german) values ('Exit','Exit','Beenden','Beende');
INSERT INTO text (text_id, english, german, swiss_german) values ('Failed','Failed','Gescheitert','Gfailt');
INSERT INTO text (text_id, english, german, swiss_german) values ('FearLevel','Fear Strength','Furchtstärke','Angschtstärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('StunLevel','Stun Strength','Betäubungsstärke','Betäubigsstärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('FifthSpell','5. Spell','5. Zauber','5. Zauber');
INSERT INTO text (text_id, english, german, swiss_german) values ('FireDamage','Fire Damage','Feuerschaden','Füürschade');
INSERT INTO text (text_id, english, german, swiss_german) values ('FireResistance','Fire Resistance','Feuerresistenz','Füürresistenz');
INSERT INTO text (text_id, english, german, swiss_german) values ('FirstSpell','1. Spell','1. Zauber','1. Zauber');
INSERT INTO text (text_id, english, german, swiss_german) values ('FourthSpell','4. Spell','4. Zauber','4. Zauber');
INSERT INTO text (text_id, english, german, swiss_german) values ('Fullscreen','Fullscreen','Vollbild','Vollbild');
INSERT INTO text (text_id, english, german, swiss_german) values ('GameSaved','Game saved','Spiel gespeichert','Spiel gspeicheret');
INSERT INTO text (text_id, english, german, swiss_german) values ('Gems','Gems','Edelsteine','Edelstei');
INSERT INTO text (text_id, english, german, swiss_german) values ('GemSockets','Gem Sockets','Edelstein Sockel','Edelstei Sockel');
INSERT INTO text (text_id, english, german, swiss_german) values ('GemSocket','Gem Socket','Edelstein Sockel','Edelstei Sockel');
INSERT INTO text (text_id, english, german, swiss_german) values ('German','German','Deutsch','Düütsch');
INSERT INTO text (text_id, english, german, swiss_german) values ('GodmodeActivated','Godmode activated','Godmode aktiviert','Godmode aktiviert');
INSERT INTO text (text_id, english, german, swiss_german) values ('GodmodeDeactivated','Godmode deactivated','Godmode deaktiviert','Godmode deaktiviert');
INSERT INTO text (text_id, english, german, swiss_german) values ('Gold','Gold','Gold','Gold');
INSERT INTO text (text_id, english, german, swiss_german) values ('GoldValue','Gold Value','Goldwert','Goldwert');
INSERT INTO text (text_id, english, german, swiss_german) values ('Haste','Haste','Schnelligkeit','Schnelligkeit');
INSERT INTO text (text_id, english, german, swiss_german) values ('Heal','Heal','Heilung','Heilig');
INSERT INTO text (text_id, english, german, swiss_german) values ('Health','Health','Lebensenergie','Lebe');
INSERT INTO text (text_id, english, german, swiss_german) values ('HealthRegeneration','Health Regeneration','Lebensregeneration','Lebensregeneration');
INSERT INTO text (text_id, english, german, swiss_german) values ('HealthRegenerationPerS','Health Regeneration / s','Lebensregeneration / s','Lebensregeneration / s');
INSERT INTO text (text_id, english, german, swiss_german) values ('Hint','Hint','Tipp','Tipp');
INSERT INTO text (text_id, english, german, swiss_german) values ('Hints','Hints','Tipps','Tipps');
INSERT INTO text (text_id, english, german, swiss_german) values ('HolyPower','Holy Power','Heilige Kraft','Heiligi Chraft');
INSERT INTO text (text_id, english, german, swiss_german) values ('IceDamage','Ice Damage','Eisschaden','Iisschade');
INSERT INTO text (text_id, english, german, swiss_german) values ('IceResistance','Ice Resistance','Eisresistenz','Iisresistenz');
INSERT INTO text (text_id, english, german, swiss_german) values ('Immune','Immune','Immun','Immun');
INSERT INTO text (text_id, english, german, swiss_german) values ('Interact','Interact','Interagieren','Interagiere');
INSERT INTO text (text_id, english, german, swiss_german) values ('Inventory','Inventory','Inventar','Inventar');
INSERT INTO text (text_id, english, german, swiss_german) values ('IsLocked','Is locked!','Ist verschlossen!','Da isch abgschlosse!');
INSERT INTO text (text_id, english, german, swiss_german) values ('Journal','Journal','Tagebuch','Tagebuech');
INSERT INTO text (text_id, english, german, swiss_german) values ('Jump','Jump','Springen','Springe');
INSERT INTO text (text_id, english, german, swiss_german) values ('KeyBindings','Key Bindings','Tastaturbelegung','Tastaturbelegig');
INSERT INTO text (text_id, english, german, swiss_german) values ('KeyReserved','This key is reserved and cannot be selected.','Diese Taste ist reserviert und kann nicht gewählt werden.','Die Taste isch reserviert und derf me nid bruche.');
INSERT INTO text (text_id, english, german, swiss_german) values ('Keys','Keys','Schlüssel','Schlüssel');
INSERT INTO text (text_id, english, german, swiss_german) values ('Killed','Killed','Getötet','Killt');
INSERT INTO text (text_id, english, german, swiss_german) values ('Feared','Feared','Verängstigt','Verängstigt');
INSERT INTO text (text_id, english, german, swiss_german) values ('Stunned','Stunned','Betäubt','Betäubt');
INSERT INTO text (text_id, english, german, swiss_german) values ('GargoyleStrength','Gargoyle Strength','Gargoyle-Stärke','Gargoyle-Stärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('Language','Language','Sprache','Sproch');
INSERT INTO text (text_id, english, german, swiss_german) values ('Level','Level','Stufe','Level');
INSERT INTO text (text_id, english, german, swiss_german) values ('Lever','Lever','Hebel','Hebel');
INSERT INTO text (text_id, english, german, swiss_german) values ('LightDamage','Light Damage','Lichtschaden','Liechtschade');
INSERT INTO text (text_id, english, german, swiss_german) values ('LightResistance','Light Resistance','Lichtresistenz','Liechtresistenz');
INSERT INTO text (text_id, english, german, swiss_german) values ('Load','Load','Laden','Lade');
INSERT INTO text (text_id, english, german, swiss_german) values ('LoadGame','Load Game','Spiel laden','Spiel lade');
INSERT INTO text (text_id, english, german, swiss_german) values ('Loading','Loading...','Lädt...','Es ladet...');
INSERT INTO text (text_id, english, german, swiss_german) values ('LockpickLevel','Lockpick Level','Dietrich Stufe','Dietrich Level');
INSERT INTO text (text_id, english, german, swiss_german) values ('Map','Map','Karte','Charte');
INSERT INTO text (text_id, english, german, swiss_german) values ('MaxFPS','Max. FPS','Max. FPS','Max. FPS');
INSERT INTO text (text_id, english, german, swiss_german) values ('MaxHealthPoints','Max. Health','Max. Lebensenergie','Max. Lebensenergie');
INSERT INTO text (text_id, english, german, swiss_german) values ('MessageNewSaveGame','Please enter the name for your new save game (at most 24 characters).','Bitte gib einen Namen ein für deinen neuen Speicherstand (höchstens 24 Zeichen).','Bitte gib en Name ih für din neue Speicherstand (höchstens 24 Zeiche).');
INSERT INTO text (text_id, english, german, swiss_german) values ('Meta','Meta','Meta','Meta');
INSERT INTO text (text_id, english, german, swiss_german) values ('Miscellaneous','Miscellaneous','Plunder','Grümpel');
INSERT INTO text (text_id, english, german, swiss_german) values ('ModifierLearned','Gem learned','Edelstein erlernt','Edelstei glernt');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLearned','Spell learned','Zauber erlernt','Zauber glernt');
INSERT INTO text (text_id, english, german, swiss_german) values ('MoveDown','Move down','Nach unten bewegen','Abelaufe');
INSERT INTO text (text_id, english, german, swiss_german) values ('MoveLeft','Move left','Nach links laufen','Links laufe');
INSERT INTO text (text_id, english, german, swiss_german) values ('MoveRight','Move right','Nach rechts bewegen','Rechts laufe');
INSERT INTO text (text_id, english, german, swiss_german) values ('MoveUp','Move up','Nach oben bewegen','Uelaufe');
INSERT INTO text (text_id, english, german, swiss_german) values ('Necromancy','Necromancy','Nekromantie','Nekromantie');
INSERT INTO text (text_id, english, german, swiss_german) values ('New','New','Neu','Neu');
INSERT INTO text (text_id, english, german, swiss_german) values ('NewGame','New Game','Neues Spiel','Neus Spiel');
INSERT INTO text (text_id, english, german, swiss_german) values ('NewJournalEntry','New journal entry','Neuer Tagebucheintrag','Neue Tagebuechiitrag');
INSERT INTO text (text_id, english, german, swiss_german) values ('No','No','Nein','Nai');
INSERT INTO text (text_id, english, german, swiss_german) values ('NoQuicksaveExists','No quick save exists','Kein Schnelllade-Speicherstand existiert','Kein Schnelllade-Speicherstand existiert');
INSERT INTO text (text_id, english, german, swiss_german) values ('NotEnoughGold','Not enough gold!','Nicht genügend Gold!','Nid gnueg Gold!');
INSERT INTO text (text_id, english, german, swiss_german) values ('NothingToSay','There''s nothing to talk about.','Es gibt nichts zu sagen.','Es git nüt zum rede.');
INSERT INTO text (text_id, english, german, swiss_german) values ('NoWeapon','No weapon','Keine Waffe','Kei Waffe');
INSERT INTO text (text_id, english, german, swiss_german) values ('NoSpells','No spells learned.','Keine Zauber gelernt.','Kei Zauber glernt.');
INSERT INTO text (text_id, english, german, swiss_german) values ('NoQuests','No quests found.','Keine Quests gefunden.','Kei Quests gfunde.');
INSERT INTO text (text_id, english, german, swiss_german) values ('NoHints','No hints learned.','Keine Tipps gelernt.','Kei Tipps glernt.');
INSERT INTO text (text_id, english, german, swiss_german) values ('NoSaves','No saves found.','Kein Speicherstand gefunden.','Kein Speicherstand gfunde.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Observed','Observed','Beobachtet','Beobachtet', 'Observado');
INSERT INTO text (text_id, english, german, swiss_german) values ('Off','Off','Aus','Uus');
INSERT INTO text (text_id, english, german, swiss_german) values ('Okay','Okay','Okay','Okee');
INSERT INTO text (text_id, english, german, swiss_german) values ('On','On','An','Ii');
INSERT INTO text (text_id, english, german, swiss_german) values ('OperationFailed','Operation failed.','Operation fehlgeschlagen.','Die Operation isch id Hose.');
INSERT INTO text (text_id, english, german, swiss_german) values ('Options','Options','Einstellungen','Iistellige');
INSERT INTO text (text_id, english, german, swiss_german) values ('Ore','Ore','Erz','Erz');
INSERT INTO text (text_id, english, german, swiss_german) values ('OutOfRange','Out of range','Ich muss näher ran','Da isch z''wiit weg');
INSERT INTO text (text_id, english, german, swiss_german) values ('Pending','Pending','Ausstehend','Nanig erfüllt');
INSERT INTO text (text_id, english, german, swiss_german) values ('Permanent','Permanent','Permanent','Permanent');
INSERT INTO text (text_id, english, german, swiss_german) values ('PhysicalDamage','Physical Damage','Physischer Schaden','Physische Schade');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('PressAnyKey','<?>','<?>','<?>','<?>');
INSERT INTO text (text_id, english, german, swiss_german) values ('Price','Price','Preis','Priis');
INSERT INTO text (text_id, english, german, swiss_german) values ('Quest','Quest','Quest','Quest');
INSERT INTO text (text_id, english, german, swiss_german) values ('QuestionDeleteSaveGame','Do you really want to delete this save game?','Willst du diesen Speicherstand wirklich löschen?','Wetsch de Speicherstand würkli lösche?');
INSERT INTO text (text_id, english, german, swiss_german) values ('QuestionGoBackToCheckpoint','Your progress since the last checkpoint will be lost. Continue?','Dein Fortschritt seit dem letzten Kontrollpunkt geht verloren. Fortfahren?','Din Fortschritt sitt em letzte Checkpoint gaht verlore. Egal?');
INSERT INTO text (text_id, english, german, swiss_german) values ('QuestionLoadGame','Load game?
All unsaved progress will be lost.','Spiel laden?
Ungespeicherter Fortschritt geht verloren.','Spiel lade?
Ungspeicherete Fortschritt isch futsch.');
INSERT INTO text (text_id, english, german, swiss_german) values ('QuestionOverwriteSaveGame','Overwrite this save game?','Diesen Speicherstand überschreiben?','De Speicherstand überschribe?');
INSERT INTO text (text_id, english, german, swiss_german) values ('QuestionStartNewGame','Start new game?
All unsaved progress will be lost.','Neues Spiel starten?
Ungespeicherter Fortschritt geht verloren.','Neus Spiel starte?
Ungspeicherete Fortschritt isch futsch.');
INSERT INTO text (text_id, english, german, swiss_german) values ('QuestItems','Quest Items','Questgegenstände','Questgegeständ');
INSERT INTO text (text_id, english, german, swiss_german) values ('Quickcast','Quickcast','Schnellzaubern','Schnellzaubere');
INSERT INTO text (text_id, english, german, swiss_german) values ('Quickload','Quick Load','Schnell Laden','Schnell Lade');
INSERT INTO text (text_id, english, german, swiss_german) values ('Quicksave','Quick Save','Schnell Speichern','Schnell Speichere');
INSERT INTO text (text_id, english, german, swiss_german) values ('Quickslot1','Quick Slot 1','Schnellwahl 1','Schnellwahl 1');
INSERT INTO text (text_id, english, german, swiss_german) values ('Quickslot2','Quick Slot 2','Schnellwahl 2','Schnellwahl 2');
INSERT INTO text (text_id, english, german, swiss_german) values ('Range','Range','Reichweite','Riichwiiti');
INSERT INTO text (text_id, english, german, swiss_german) values ('Reduction','Reduction','Verminderung','Verminderig');
INSERT INTO text (text_id, english, german, swiss_german) values ('Reflection','Reflection','Reflektion','Abpraller');
INSERT INTO text (text_id, english, german, swiss_german) values ('Reputation','Reputation','Ruf','Ruef');
INSERT INTO text (text_id, english, german, swiss_german) values ('Reset','Reset','Zurücksetzen','Zruggsetze');
INSERT INTO text (text_id, english, german, swiss_german) values ('Resume','Resume','Spiel fortsetzen','Zrugg zum Spiel');
INSERT INTO text (text_id, english, german, swiss_german) values ('Save','Save','Speichern','Speichere');
INSERT INTO text (text_id, english, german, swiss_german) values ('SaveGame','Save Game','Spiel speichern','Spiel speichere');
INSERT INTO text (text_id, english, german, swiss_german) values ('SavegameDeleted','Save game successfully deleted.','Speicherstand erfolgreich gelöscht.','Speicherstand isch glöscht.');
INSERT INTO text (text_id, english, german, swiss_german) values ('Screenshot','Screenshot','Bildschirmfoto','Bildschirmföteli');
INSERT INTO text (text_id, english, german, swiss_german) values ('SecondSpell','2. Spell','2. Zauber','2. Zauber');
INSERT INTO text (text_id, english, german, swiss_german) values ('ShadowDamage','Shadow Damage','Schattenschaden','Schatteschade');
INSERT INTO text (text_id, english, german, swiss_german) values ('ShadowResistance','Shadow Resistance','Schattenresistenz','Schatteresistenz');
INSERT INTO text (text_id, english, german, swiss_german) values ('Smoothing','Texture Smoothing','Texturen glätten','Texture verschmiere');
INSERT INTO text (text_id, english, german, swiss_german) values ('Sound','Sound','Musik','Musig');
INSERT INTO text (text_id, english, german, swiss_german) values ('SoundVolume','Sound Volume','Lautstärke Effekte','Effekt-Luutstärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('MusicVolume','Music Volume','Lautstärke Musik','Musig-Luutstärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('Speed','Speed','Geschwindigkeit','Gschwindigkeit');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellAntiGravity','Anti Gravity','Schwerkraft umkehren','Schwerchraft umchere');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellAntiGravityDesc','Reverses gravity for Cendric for a certain duration.','Dreht Cendrics Schwerkraft für eine gewisse Zeit um.','Drüllt em Cendric sini Schwerchraft für e gwüssi Ziit um.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellAureola','Aureola','Strahlenkranz','Strahlechranz');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellAureolaDesc','Sends balls of light in all directions, if they hit an enemy they will return to Cendric and heal him.','Schickt Lichtbälle in alle Richtungen, die zurückkehren und Cendric heilen, falls sie einen Gegner treffen.','Schickt Liechtbäll in all Richtige, wo zruggchömed und de Cendric heiled wenn si en Gegner troffe hend.');
INSERT INTO text (text_id, english, german, swiss_german) values ('Spellbook','Spellbook','Zauberbuch','Zauberbuech');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellDivineShield','Divine Shield','Göttlicher Schild','Göttlichs Schild');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellDivineShieldDesc','Grants a shield that enhances Cendrics resistances and heals him once.','Umhüllt Cendric mit einem Schild, der ihn einmalig heilt und für eine gewisse Dauer seine Resistenzen erhöht.','Umhüllt de Cendric mitme Schild wo ihn eimalig heilt und sini Resistenze für e gwüssi Ziit erhöht.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellFear','Fear','Furcht','Angscht');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellFearDesc','Enemies will flee in terror for a certain duration if the spell is strong enough.','Gegner fliehen für eine gewisse Zeit, allerdings nur, wenn der Zauber genug stark für sie ist.','Gegner flüchtet für e gwüssi Ziit, aber nur, wenn de Zauber gnueg starch isch für si.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellFireBall','Fireball','Feuerball','Füürball');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellFireBallDesc','The good old fireball. Burns enemies and melts ice.','Der gute alte Feuerball. Verbrennt Gegner und schmilzt Eis.','De guet alt Füürball. Verbrennt Gegner und schmelzt Iis.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellIceBall','Iceball','Eisball','Iisball');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellIceBallDesc','An icy ball damages enemies and freezes water.','Ein eisiger Ball schadet Gegnern und gefriert Wasser.','En iisige Ball schadet Gegner und gfrüürt Wasser.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellFlash','Flash','Blitz','Blitz');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellFlashDesc','Cendric dashes forward with speed of light, ignores most blocks and damages enemies.','Cendric schiesst mit Lichtgeschwindigkeit vorwärts, ignoriert die meisten Blöcke und schadet Gegner.','De Cendric schüsst mit Liechtgschwindigkeit vorwärts, ignoriert di meiste Blöck und schadet Gegner.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellIcyAmbush','Icy Ambush','Eisiger Hinterhalt','Iischalte Hinterhalt');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLight','Light','Licht','Liecht');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLightDesc','There shall be light!','Es werde Licht!','Chasch chli heller mache, bitte?');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellIcyAmbushDesc','Cendric throws an enchanted dagger that deals big damage when it hits an enemy, stuns it and enemies in range and ports Cendric to its location.','Cendric wirft einen verzauberten Dolch, der eine grosse Menge Schaden verursacht, wenn er einen Gegner trifft und Cendric an dessen Stelle teleportiert. Gegner im Umkreis werden betäubt.','De Cendric wirft en verzauberte Dolch wo viel Schade amne Gegner macht und Gegner im Umkreis betäubt. De Cendric wird ad Stell vom troffene Gegner teleportiert.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLeech','Leech','Lebensraub','Lebesraub');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLeechDesc','Sends out leeching spells that damage enemies and return to Cendric to heal  him if they hit an enemy.','Schickt lebensraubende Zauber aus, die zu Cendric zurückkehren, um ihn zu heilen, falls sie einen Gegner getroffen haben.','Schickt lebensraubendi Zauber uus wo zum Cendric zruggchömed zum ihn heile falls si en Gegner troffe hend.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLeapOfFaith','Leap of Faith','Glaubenssprung','Glaubessprung');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellLeapOfFaithDesc','A holy power flows through Cendric, enabling him to jump higher and fall slower for a certain duration.','Eine heilige Kraft durchströmt Cendric, die ihn höher springen und langsamer fallen lässt.','E heiligi Kraft durchströmt de Cendric, mit dere er höcher springe und langsamer falle chan.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellShadowTrap','Shadow Trap','Schattenfalle','Schattefalle');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellShadowTrapDesc','Cendric places a shadow trap on the ground that stuns enemies and deals damage over time when triggered.','Cendric platziert eine Schattenfalle am Boden, die Gegner betäubt und Schaden über Zeit verursacht, wenn sie ausgelöst wird.','De Cendric setzt e Schattefalle uf de Bode wo Gegner betäubt und Schade über Ziit macht wenn si usglöst wird.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellRaiseTheDead','Raise The Dead','Tote Erwecken','Toti Erwecke');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellRaiseTheDeadDesc','Raises fallen enemies that will fight for Cendric for a certain duration, if the spell is strong enough.','Erweckt gefallene Gegner wieder, die für eine gewisse Zeit für Cendric kämpfen, falls der Zauber genügend stark ist.','Erweckt toti Gegner wider und laht si für e gwüssi Ziit für de Cendric kämpfe, falls de Zauber gnueg starch isch.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellHolyFire','Holy Fire','Heiliges Feuer','Heiligs Füür');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellHolyFireDesc','Cendric summons a holy fire that burns enemies in range.','Cendric beschwört ein heiliges Feuer, das Gegner in der Nähe verbrennt.','De Cendric beschwört es heiligs Füür wo Gegner ide Nöchi verbrennt.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellSummonGargoyle','Summon Gargoyle','Gargoyle Beschwören','Gargoyle Beschwöre');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellSummonGargoyleDesc','Cendric summons a mighty Gargoyle that serves him and attacks enemies.','Cendric beschwört einen mächtigen Gargoyle, der Gegner attackiert.','De Cendric beschwört en mächtige Gargoyle wo Gegner aagrift.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellSlots','Spell Slots','Verfügbare Zauber','Verfüegbari Zauber');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellUnlock','Summon Picklock','Dietrich beschwören','Dietrich beschwöre');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellUnlockDesc','Summons a picklock that is able to unlock locked chests if its strength is big enough for the chest.','Beschwört einen Dietrich, der verschlossene Truhen knackt, sofern die Stärke des Zaubers ausreicht.','Beschwört en Dietrich ane wo e verschlosseni Chischte knackt sofern de Zauber gnueg starch isch für die Chischte.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellWindGust','Wind Gust','Windstoss','Windstoss');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellWindGustDesc','A wind gust that is able to shift certain objects.','Ein Windstoss der gewisse Objekte verschieben kann.','En Windstoss wo gwüssi Objekt verschiebe chan.');
INSERT INTO text (text_id, english, german, swiss_german) values ('StartGame','Start Game','Spiel starten','Spiel starte');
INSERT INTO text (text_id, english, german, swiss_german) values ('Stats','Stats','Statuswerte','Statuswert');
INSERT INTO text (text_id, english, german, swiss_german) values ('Strength','Strength','Stärke','Stärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('SwissGerman','Swiss German','Schweizerdeutsch','Schwiizerdüütsch');
INSERT INTO text (text_id, english, german, swiss_german) values ('ThirdSpell','3. Spell','3. Zauber','3. Zauber');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToggleTooltips','Toggle Tooltips','Tooltips anzeigen/verbergen','Tooltips zeige/verstecke');
INSERT INTO text (text_id, english, german, swiss_german) values ('Twilight','Twilight','Zwielicht','Dämmerig');
INSERT INTO text (text_id, english, german, swiss_german) values ('Type','Type','Typ','Typ');
INSERT INTO text (text_id, english, german, swiss_german) values ('Unknown','Unknown','Unbekannt','Unbekannt');
INSERT INTO text (text_id, english, german, swiss_german) values ('Unsalable','Cannot be sold','Unverkäuflich','Unverchäuflich');
INSERT INTO text (text_id, english, german, swiss_german) values ('Waypoint','Waypoint','Wegmarke','Wägpunkt');
INSERT INTO text (text_id, english, german, swiss_german) values ('WaypointNotActive','Waypoint not active!','Wegmarke ist nicht aktiv!','De Wägpunkt isch nid aktiv!');
INSERT INTO text (text_id, english, german, swiss_german) values ('WaypointActivated','Waypoint activated','Wegmarke aktiviert','Wägpunkt aktiviert');
INSERT INTO text (text_id, english, german, swiss_german) values ('WeaponDamage','Weapon Damage','Waffenschaden','Waffeschade');
INSERT INTO text (text_id, english, german, swiss_german) values ('WindForce','Wind Force','Windstärke','Windstärchi');
INSERT INTO text (text_id, english, german, swiss_german) values ('Window','Window','Fenster','Fenster');
INSERT INTO text (text_id, english, german, swiss_german) values ('WindowedFullscreen','Full Window','Vollbild im Fenster','Vollbild im Fenster');
INSERT INTO text (text_id, english, german, swiss_german) values ('Yes','Yes','Ja','Ja');
INSERT INTO text (text_id, english, german, swiss_german) values ('VSync','Vsync','Vsync','Vsync');
INSERT INTO text (text_id, english, german, swiss_german) values ('GhostDamage','Ghost Damage','Geisterschaden','Geisterschade');
INSERT INTO text (text_id, english, german, swiss_german) values ('ScreenshotSaved','Screenshot saved','Bildschirmfoto gespeichert','Bildschirmföteli gspeicheret');
INSERT INTO text (text_id, english, german, swiss_german) values ('Sign','Sign','Schild','Schild');
INSERT INTO text (text_id, english, german, swiss_german) values ('Spanish','Spanish','Spanisch','Spanisch');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellTelekinesis','Telekinesis','Telekinese','Telekinese');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellTelekinesisDesc','What seemed to be far is now near.','Das, was unerreichbar schien, ist nun greifbar geworden.','Unerreichbar isch es Fremdwort worde.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellGhostForm','Ghost Form','Geistergestalt','Geistergstalt');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellGhostFormDesc','Cendric takes the shape of a ghost, making him able to walk through certain blocks, walk faster and gain additional weapon damage.','Cendric nimmt eine Geisterform an, was ihn durch bestimmte Blöcke gehen lässt, ihn schneller macht und ihm zusätzlichen Waffenschaden gewährt.','De Cendric nimmt e Geisterform ah, mit dere er dur gwüssi Blöck laufe cha, schneller lauft und me Waffeschade het.');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellInvisibility','Invisibility','Unsichtbarkeit','Unsichtbarkeit');
INSERT INTO text (text_id, english, german, swiss_german) values ('SpellInvisibilityDesc','Renders Cendric invisible for a certain duration for certain enemies','Cendric wird unsichtbar für eine gewisse Zeit und für gewisse Gegner.','Cendric wird unsichtbar für e gwüssi Ziit und gwüssi Gegner.');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToInteract','to interact','- interagieren','zum interagiere');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToTalk','to talk','- reden','zum rede');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToCook','to cook','- kochen','zum choche');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToPickup','to pickup','- aufnehmen','zum neh');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToLoot','to loot','- plündern','zum neh');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToActivate','to activate','- aktivieren','zum aktiviere');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToRead','to read','- lesen','zum läse');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToSwitch','to toggle','- umschalten','zum drucke');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToSteal','to steal','- stehlen','zum chlaue');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToOpen','to open','- öffnen', 'zum ufmache');
INSERT INTO text (text_id, english, german, swiss_german) values ('ToMine','to mine','- abbauen', 'zum abbaue');
INSERT INTO text (text_id, english, german, swiss_german) values ('NeedPickaxe','You need a pickaxe to mine ore.','Du brauchst eine Spitzhacke um Erz abzubauen.', 'Du bruchsch en Pickel zum Erz hacke.');
INSERT INTO text (text_id, english, german, swiss_german) values ('NothingToGain','Nothing to gain there anymore.','Da ist nichts mehr zu holen.', 'Da gits nüt me z''hole.');
INSERT INTO text (text_id, english, german, swiss_german) values ('InvisibilityLevel','Transparency','Transparenz','Transparenz');
INSERT INTO text (text_id, english, german, swiss_german) values ('Fireplace','Fireplace','Kochstelle','Chochstell');
INSERT INTO text (text_id, english, german, swiss_german) values ('NothingToCook','[Nothing to cook...]','[Nichts zu kochen...]','[Es git nüt zum chochä...]');
INSERT INTO text (text_id, english, german, swiss_german) values ('LeverStuck','The lever is stuck!','Der Hebel ist verklemmt!','De Hebel isch verchlemmt!');
INSERT INTO text (text_id, english, german, swiss_german) values ('Used','Used ','Benutzt: ','Brucht: ');
INSERT INTO text (text_id, english, german, swiss_german) values ('','','','');