INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_purpleback', 'item', 'Purple cape','Violetter Umhang','Violette Umhang');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_ringoflesserhealth', 'item', 'Small ruby ring','Kleiner Rubinring','Chliine Rubinring');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_wizardhatblue', 'item', 'Blue wizardhat','Blauer Spitzhut','Blaue Magierhuet');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_wizardhatgrey', 'item', 'Grey wizardhat','Grauer Spitzhut','Graue Magierhuet');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_bread', 'item', 'Bread','Brot','Brot');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_caveberry', 'item', 'Cave berries','Höhlenbeeren','Höhlebeeri');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_cheese', 'item', 'Cheese','Käse','Chääs');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_glowingshroom', 'item', 'Glowing shroom','Leuchtpilz','Lüchtpilz');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_healingherb', 'item', 'Healing herb','Heilpflanze','Heilpflanze');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_water', 'item', 'Water bottle','Wasserflasche','Wasserfläsche');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('go_onecoin', 'item', 'Golden coin','Goldmünze','Goldmünze');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('go_threecoins', 'item', 'A few coins','Ein paar Münzen','Es paar Münze');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('mi_goldengoblet', 'item', 'Golden goblet','Goldener Pokal','Goldige Pokal');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('qe_letter', 'item', 'Sealed Letter','Versiegelter Brief','Versiglete Brief');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('qe_letter', 'item_text', 'Dear king
bla bla blaaaaaaaa bla blaaaa bla bla and you better bla bla soon! CU your enemy.','Lieber König
blabla blaaaaaaaa bla bla bla lblaaaaa bla und sowieso','Liebe König
bla blubb bla bla bli bla blaaaaaaaa bla ende.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_icestaff', 'item', 'Ice staff','Eisstab','Iisstab');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_rustysword', 'item', 'Rusty sword','Rostiges Schwert','Rostigs Schwert');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_bread', 'item_desc', 'An ordinary loaf of bread.','Ein einfaches Brot.','Es Brot halt.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_caveberry', 'item_desc', 'Sweet','Süss','Süess');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_cheese', 'item_desc', 'Smelly.','Riecht nicht sonderlich gut.','Er müffelet echli.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_glowingshroom', 'item_desc', 'It still glows...','Er leuchtet immer noch...','Er lüchtet immer na...');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('mi_goldengoblet', 'item_desc', 'A golden goblet','Ein goldener Pokal','En goldige Pokal');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_healingherb', 'item_desc', 'Heals wounds','Heilt Wunden','Heilt Wunde');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_icestaff', 'item_desc', 'Feels ice cold.','Fühlt sich eiskalt an.','So chalt we Iis.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('qe_letter', 'item_desc', 'Sealed','Versiegelt','Versiglet');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_purpleback', 'item_desc', 'Ugly cape for testing. Needs some shading. Won''t appear in the final version.','Hässlicher Umhang, nur für Testing. Wird vermutlich nicht in dem Endgame auftauchen und wird entfernt.','Boaey we chame nur sonen hässliche Umhang designe, gaht ja gar nid. Schomal was vo Schatte und so ghört? Alteeeee');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_ringoflesserhealth', 'item_desc', 'The small ruby sparkles','Der kleine Rubin funkelt','De chli Rubin funklet');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_rustysword', 'item_desc', 'This sword has seen better days.','Das Schwert hat schon bessere Tage gesehen.','Da Schwert het glaub scho besseri Täg gse.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_water', 'item_desc', 'Fresh clear water.','Frisches klares Wasser.','Frischs klars Wasser.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_wizardhatblue', 'item_desc', 'A perfect fit for a mage.','Perfekt für einen Magier.','Perfekt für en Magier.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_wizardhatgrey', 'item_desc', 'A perfect fit for a mage.','Perfekt für einen Magier.','Perfekt für en Magier.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_head_necrot3', 'item', 'Shadow Cowl','Schattengugel','Schattegugle');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_head_necrot3', 'item_desc', 'Shields perfectly against any light','Schirmt perfekt jedwedes Licht ab.','Schirmt perfekt ab gege Liecht.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_back_necrot3', 'item', 'Shadow Cloak','Schattenumhang','Schatteumhang');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_back_necrot3', 'item_desc', 'A pliant piece of cloth.','Ein geschmeidiges Stück Stoff.','Es gschmeidigs Stück Stoff.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_body_necrot3', 'item', 'Horned Scalemail','Gehörnter Schuppenpanzer','Ghörnte Schuppepanzer');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_body_necrot3', 'item_desc', 'Only those who have proven themselves worthy to the necromancers of Admantris are allowed to wear that piece of armour.','Nur diejenigen, die sich bei den Nekromanten von Admantris als würdig erwiesen haben, dürfen diese Rüstung tragen.','Nur die, wo sich bide Nekromante vo Admantris als würdig erwise hend, derfed die Rüstig träge.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_rafishat', 'item', 'Rafis Hat','Rafis Hut','Rafis Huet');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_rafishat', 'item_desc', 'What a strange hat...','Was für ein seltsamer Hut...','Was füren komische Huet...');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_head_divinet3', 'item', 'Circlet of the Order','Reif des Ordens','Reif vom Orde');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('eq_head_divinet3', 'item_desc', 'Golden & shiny','Golden & glänzig','Goldig & glänzig');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_lesserhealingpotion', 'item', 'Lesser Healing Potion','Geringer Heiltrank','Chliine Heiltrank');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_lesserhealingpotion', 'item_desc', '...','...','...');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_rawmeat', 'item', 'Raw Meat','Rohes Fleisch','Rohs Fleisch');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_rawmeat', 'item_desc', 'Would taste better if it was roasted on a fire.','Würde gebraten noch besser schmecken.','Wär chli feiner wenmes wür brötle.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_roastedmeat', 'item', 'Roasted Meat','Gebratenes Fleisch','Brotes Fleisch');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('fo_roastedmeat', 'item_desc', 'A juicy piece of meat, seared, just as it should be.','Ein saftiges Stück Fleisch, kurz angebraten, wie es sein soll.','Es saftigs Stück Fleisch, churz abrote, genau wes sii söt.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_torch', 'item', 'Torch','Fackel','Fackle');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_torch', 'item_desc', 'Lights the way.','Spendet Licht.','Git Liecht.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_oathbreaker', 'item', 'Oathbreaker','Eidbrecher','Eidbrecher');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('we_oathbreaker', 'item_desc', 'The legendary twin-daggers Oath and Breaker. Some say that the cyan stones hold captured souls.','Die legendären Zwillingsdolche Eid und Brecher. Es wird erzählt, dass die zyanblauen Steine gefangene Seelen beherrbergen.','Di legendäre Zwillingsdolch Eid und Brecher. Me munklet dass ide zyanblaue Stei Seele gfange sind.');