INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Rat','enemy','Rat','Ratte','Ratte');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('FireRat','enemy','Fire Rat','Feuerratte','Füürratte');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Nekomata','enemy','Nekomata','Nekomata','Nekomata');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Crow','enemy','Crow','Krähe','Raab');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Skeleton','enemy','Skeleton','Skelett','Skelett');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Gargoyle','enemy','Gargoyle','Gargoyle','Gargoyle');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Hunter','enemy','Edmond','Edmond','Edmond');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Wisp','enemy','Wisp','Irrlicht','Irrliecht');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Seagull','enemy','Seagull','Möwe','Möwe');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Wolf','enemy','Wolf','Wolf','Wolf');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Cairn','enemy','Cairn Wraith','Cairn Geist','Cairn Geist');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('MysteriousBeast','enemy','Mysterious Beast','Mysteriöses Biest','Mysteriöses Biescht');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('CavernBeast','enemy','Cavern Beast','Höhlenmonster','Höhlemonster');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BossWolf','enemy','Khajag, the Cavern Guardian','Khajag, Wächter der Höhlen','Khajag, Wächter vode Höhlene');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BossZeff','enemy','Zeff','Zeff','Zeff');