INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('BookRhendalMagic','document','Thoughts on
Magic
- Rhendal','Gedanken zu
Magie
- Rhendal','Gedanke zu 
Magie
- Rhendal');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('TitleRhendalMagic1','document','I - Magic','I - Magie','I - Magie');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ContentRhendalMagic1','document','The omnipresence of magic is the first thing we need to understand when dealing with this topic. It is an energy that flows through this world, through the ground, the air and every living creature. There is no homogenous distribution though, it concentrates in magical artefacts or at special places. 

The magic itself has been there as long as we can remember and we''re not entirely sure where it originates from.','Das erste, was man verstehen muss, wenn man sich mit diesem Thema beschäftigt, ist die Allumfänglichkeit der Magie. Es ist eine Energie, die durch diese Welt fliesst, durch die Erde, die Luft und durch jedes lebendige Wesen. Die Magie ist allerdings nicht gleichverteilt im Raum, sie konzentriert sich in magischen Artefakten oder an speziellen Orten.

Die Magie an sich gibt es schon, so weit wir uns zurückerinnern können und wir sind uns nicht sicher, wo sie ihren Ursprung genommen hat.','Es erste womer mönd versto, wennmer üs mit dere Materie befassed, isch, dass Magie allumfänglich isch. Es isch e Energie wo dur die Welt flüsst, dur d''Erde, dur d''Luft und dur jedes lebendige Wäse. D''Magie isch allerdings nid gliichverteilt im Ruum, si konzentriert sich in magische Artefakt oder an spezielle Ort.

D''Magie selber gits scho, so wiit mer üs zrugg bsinne möged und mer sind üs nid sicher, wo si genau her chunt.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ContentRhendalMagic2','document','There are explanations, of course, and the probably most famous one is the theory the Clerics are spreading. They believe to know that their "Eternal Light" has gifted us with that power, and that the "Enlighted" are the chosen ones who can make use of that divine energy.

A problem with this theory is that not only the ones who believe in this "God of Light" are able to use magic. Magic comes in quite different forms, but the Clerics consider any other form as inferior. This narrow minded thinking is what discourages me to have a deeper conversation with them. I feel that magic is more than that.','Es gibt natürlich Erklärungen dazu, und die vermutlich bekannteste ist die Theorie, welche die Kleriker verbreiten. Sie glauben zu wissen, dass ihr "Ewiges Licht" uns diese Kraft vermacht hat und dass die "Erleuchteten" die Erwählten sind, die diese göttliche Kraft nutzen können.

Dieser Theorie widerspricht jedoch dass nicht nur diejenigen, die an diesen "Lichtgott" glauben, Magie benutzen können. Es gibt nämlich verschiedene andere Formen von Magie, welche die Kleriker jedoch als minderwertig abtun. Dieses eingeschränkte Denken ist es, was mich davon abhält, mit ihnen eine tiefere Konversation zu haben. Ich spüre, Magie ist mehr als nur das.','Es git natürli scho Erchlärige dezue, und di bekanntischt devo isch d''Theorie, wod Kleriker verbreitet. Si glaubed nämlich, dass ihres "Ewige Liecht" üs die Chraft vermacht het und dass di "Erlüüchtete" di Erwählte sind, wo sich die göttlich Chraft zu Nutze mache chönd.

Wa dere Theorie aber widerspricht, isch, dass nid nur die wo a de "Liechtgott" glaubed, Magie bruuche chönd. Es git nämlich verschideni anderi Arte vo Magie, aber d''Kleriker halted die all für minderwertig. Das iigschränkti Denke isch aber genau was mich devo abhaltet, e tüüferi Konversation mit dene zha.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('TitleRhendalMagic3','document','II - Mages','II - Magier','II - Magier');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ContentRhendalMagic3','document','Mages are the ones that can make a direct use of this energy, by controlling and converting it. One does not need to be a mage though to feel it - if you''ve spent a lot of time trying to understand it, anyone can feel its presence. But not everyone will be able to control it, this is reserved for the ones who are born with this gift. Even people without this ability can still take advantage of it though, and one example is alchemy - studying the magical powers of plants and animals, and using their magic instead of controlling it directly.','Magier sind diejenigen, die die Magie direkt nutzen können, indem sie sie kontrollieren und umwandeln. Man muss aber nicht ein Magier sein, um sie zu spüren - wenn man genug Zeit damit verbracht hat, sie zu verstehen, kann jeder ihre Anwesenheit spüren. Allerdings wird nicht jeder sie kontrollieren können, das ist denjenigen vorenthalten, die mit dieser Gabe geboren sind. Auch Leute ohne diese Fähigkeit können sie aber immer noch über Umwege nutzen, und ein Beispiel dafür ist die Alchemie - das Studieren der magischen Eigenschaften von Pflanzen und Tieren.','Magier sind die, wo d''Magie direkt nutze chönd, indem si si kontrolliered und umwandlet. Me mun aber nid en Magier si, zum si gspüre - wenn me gnueg Ziit demit verbrocht het, si z''verstah, chan jede iri Aweseheit gspüre. Allerdings wird nid jede si au kontrolliere chöne, well das isch dene vorenthalte, wo mit dere Gab ufd Welt cho sind. Mir "Normalsterbliche" chönd d''Magie aber immerna über Umweg nutze, und es Biispil dadefür isch d''Alchemie - es Studiere vode magische Eigeschafte vo Pflanze und Tier.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ContentRhendalMagic4','document','As interesting and beneficial it may be, there are a lot of people who are afraid of its presence, especially when they can neither feel nor understand it. This is entirely comprehensible, of course, and even I myself am sceptical about what it can be used for. Nevertheless, I''m still planning on dedicating the rest of my life to the studies of this utterly fascinating matter.','Man kann diese Eigenschaften so auch für sich nutzen, ohne die Magie direkt zu kontrollieren. 

Aber so interessant und nützlich die Magie auch sein mag, es gibt viele Menschen, welche sich vor ihr fürchten. Das ist natürlich völlig verständlich, auch ich selbst bin skeptisch, wenn ich sehe, für was sie verwendet werden kann. Trotzdem habe ich immer noch vor, mich für den Rest meines Lebens den Studien dieses äusserst interessanten Themas zu widmen.','Me chan die Eigeschafte au so für sich nutze, ohni d''Magie direkt z''kontrolliere.

Aber so interessant und nützlich d''Magie au sii mag, es git viel Lüüt, wo de Bammel hend devor. Da isch natürli völlig verständlich, au ich bin emel skeptisch, wenn ich gse, für was me si so bruuche chan. Trotzdem hani immerna vor, de Rest vo mim Läbe mitem Studium vo dem üsserst interessante Thema z''widme.');



