INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_rats_nest','quest','The Rats'' Nest','Das Rattennest','Es Rattenest');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_rats_nest', 'quest_desc','The hunter Edmond asked me to search for the rats nest and kill the rats that live there.','Der Jäger Edmond hat mich gebeten, das Rattennest zu suchen und die Ratten, die dort hausen, zu töten.','De Jäger Edmond wür gern dass ich es Rattenest suech und die Ratte töte wo det läbed.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('who_am_i','quest','Who am I?','Wer bin ich?','Wer bin ich?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('who_am_i', 'quest_desc','I''ve awoken in a forest, alone and without any memory. I should find out how I got here and who I am. The only thing I remember is my name: Cendric.','Ich bin alleine in einem Wald erwacht, ohne jegliche Erinnerung. Ich sollte herausfinden, wie ich hierher gekommen bin und wer ich überhaupt bin. Das einzige, an das ich mich erinnere, ist mein Name: Cendric.','Ich bi elei imne Wald ufgwacht, ohni irgendwelchi Erinnerige. Ich söt glaub zersch mal usefinde, wie ich da ane cho bin und wer ich überhaupt bin. Es einzig, a das ich mich erinnere chan, isch min Name: Cendric.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('who_am_i', 'quest_desc_1','The village elder may help me with my problem.','Der Dorfälteste könnte mir mit meinem Problem helfen.','De Dorfältist chan mer vilicht mit mim Problem wiiterhelfe.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('meat_delivery','quest','Meat Delivery','Fleischlieferung','Fleisch Liferig');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('meat_delivery', 'quest_desc','I have to bring the five pieces of meat Edmond gave me to the cook Ingrid. I can find her in the village.','Ich soll die fünf Stücke rohes Fleisch, die mir Edmond gegeben hat, ins Dorf zur Köchin Ingrid bringen.','Ich söll füf Stück rohs Fleisch womer de Edmond gä het zude Chöchin Ingrid im Dorf bringe.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('roast_meat_for_ingrid','quest','Roasted Meat for Ingrid','Fleisch braten für Ingrid','Fleisch brötle für Ingrid');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('roast_meat_for_ingrid', 'quest_desc','I should roast the five pieces of meat Ingrid gave me on a fireplace.','Ich soll die fünf Stücke Fleisch die mir Ingrid gegeben hat an einer Feuerstelle braten.','Ich söll die füf Stück Fleisch womer d''Ingrid gä het anere Füürstell brötle.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('silkweed_potion','quest','The Silkweed Potion','Der Seidenkrauttrank','De Sidechrütlitrank');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('silkweed_potion', 'quest_desc','I have to look for a Silkweed in the elder''s garden so he can brew me a potion to get my memories back.','Ich soll im Garten des Dorfältesten nach Seidenkraut suchen, so dass er mir einen Trank brauen kann, der meine Erinnerungen zurück bringt.','Ich söll im Garte vom Dorfältiste nachme Sidechrütli sueche, so dass er mir es Tränkli braue chan wo mini Erinnerige zrugg bringt.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('hawthorn_staff','quest','The Hawthorn Staff','Der Weissdorn-Stab','De Wissdorn-Stab');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('hawthorn_staff', 'quest_desc','The elder grows a magical tree in his garden, I should break off one of its branches and use it as a staff.','Der Älteste züchtet einen magischen Baum in seinem Garten, von dem ich einen Ast abbrechen kann, um ihn als Stab zu nutzen.','De Ältist het i sim Garte es magisches Bäumli vo dem ich mir en Ast abbreche söt zum en als Stab bruche.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_mark','quest','The Mark','Das Mal','Es Zeiche');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_mark', 'quest_desc','A strange mark appeared on my wrist after I''ve drunk the Silkweed potion. I don''t remember anything about it and should find out more.','Ein seltsames Mal ist auf meinem Handgelenk erschienen nachdem ich den Seidenkrauttrank getrunken habe. Ich kann mich nicht daran erinnern und sollte mehr darüber herausfinden.','Es komisches Zeiche isch fürecho nachdem ich de Sidechrütlitrank trunke ha. Ich chan mich nid dra erinnere und söt me drüber usefinde.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_mark', 'quest_desc_1','The mark is probably an evil curse. I should find someone who knows more and is able to break it.','Das Mal ist wahrscheinlich ein böser Fluch. Ich sollte jemanden finden, der mehr darüber weiss und ihn brechen kann.','Es Zeiche isch wahrschinds en böse Fluech. Ich söt öpper finde, wo me drüber weiss und ihn breche chan.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_mark', 'quest_desc_2','The cleric Inina told me that it is probably a curse designed to track me. She told me to ask the alchemist Syrah who lives in Gandria for advice.','Die Klerikerin Inina hat mir gesagt, dass es sich dabei wahrscheinlich um einen Fluch handelt, der jemandem meinen Aufenthaltsort verrät. Ich sollte die Alchemistin Syrah, die in Gandria lebt, um Rat fragen.', 'D''Klerikerin Inina het mer gseit, dass da Zeiche wahrschinlich en Fluech isch, wo verratet, wo ich grad so bin. Ich sött d''Alchemistin Syrah, wo in Gandria lebt, um Rot fröge.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('the_mark', 'quest_desc_3','Syrah told me about a guy in the Basilisk inn that has a similar mark.','Syrah hat mir von einem Typen im Gasthaus zum Basilisken erzählt, der ein ähnliches Mal hat.', 'D''Syrah het mer vomne Typ im Gasthuus zum Basilisk verzellt, wo es ähnlichs Zeiche het.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('broken_bridge','quest','The Broken Bridge','Die kaputte Brücke','Di kabutt Brugg');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('broken_bridge', 'quest_desc','The bridge that connects the village and tavern is broken. Using my magic, I should be able to freeze the river and get to the other side, to get the Elder a bottle of "Feudal Fire"','Die Brücke, die das Dorf und die Taverne verbindet, ist kaputt. Ich sollte mithilfe meiner Magie auf die andere Seite des Flusses gelangen und dem Ältesten eine Flasche "Feudales Feuer" von der Taverne holen.','D''Brugg wo es Dorf und Taverne verbindet isch kabutt. Ich sött de Fluss gfrüre chöne und so uf di ander Siite cho, zum em Älteste e Fläsche "Feudals Füür" bringe.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('monster_problem','quest','The Monster Problem','Das Monsterproblem','Es Monsterproblem');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('monster_problem', 'quest_desc','The farmers of the Meadows are having troubles with a monster that keeps stealing their sheep.','Die Bauern vom Mittelland haben Probleme mit einem Monster, das ihnen immer wieder Schafe stiehlt.','D''Buure vom Mittelland hend es Problem mitme Monster wo ihne immer wider Schöfli chlaut.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('monster_problem', 'quest_desc_1','No one has really seen the beast so far. But Thea claims that she''s seen it disappear into the South.','Niemand hat das Biest bisher wirklich zu Gesicht bekommen. Aber Thea behauptet, sie hätte es in den Süden verschwinden sehen.','Niemert het das Biescht bis jetzt würkli gse. Aber d''Thea behauptet, dass si gse het, wes in Süde verschwunde isch.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('spoiled_fire','quest','Spoiled Fire','Verdorbenes Feuer','Verdorbes Füür');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('spoiled_fire', 'quest_desc','I''ve made a deal with Vincent, some shady guy, to let him mix something into the bottle before I take it to Rhendal.','Ich habe mit Vincent, einem zwielichtigen Typ, eine Abmachung getroffen, dass er etwas in die Flasche mischt, bevor ich sie Rhendal bringe.','Ich han e Abmachig mitem Vincent, emne zwielichtige Typ, gmacht, dass er öppis id Fläsche mischt, bevor ich si zum Rhendal bring.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('gates_of_gandria','quest','The Gates of Gandria','Die Tore von Gandria','Es Tor vo Gandria');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('gates_of_gandria', 'quest_desc','The city guards of Gandria won''t let me enter the city until I the mystery about the missing citizens is solved.','Die Stadtwachen von Gandria werden mich nicht in die Stadt lassen, solange das Rätsel um die verschwundenen Bürger nicht gelöst ist.','D''Stadtwache vo Gandria werded mich nid id Stadt lah solang es Rätsel um di verschwundene Bürger nid glöst isch.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('gates_of_gandria', 'quest_desc_1','The High Priestess Inina suspects that the strange magical energy around the shrine is responsible for the incidents.','Hohepriesterin Inina nimmt an, dass die seltsame magische Kraft beim Schrein für die Vorfälle verantwortlich ist.','D''Hohepriesterin Inina vermuetet, dass di komisch magisch Chraft bim Schrein für die Vorfäll verantwortlich isch.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('zeffs_curse','quest','Zeff''s Curse','Zeff''s Fluch','Em Zeff sin Fluech');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('zeffs_curse', 'quest_desc','The leatherworker Zeff was turned into a wolf by a mysterious beast. Maybe I can break the curse if I kill that thing. It hides in a cave outside the city.','Der Lederer Zeff wurde von einem mysteriösen Biest in einen Wolf verwandelt. Vielleicht kann ich den Fluch brechen, wenn ich das Ding töte. Es versteckt sich in einer Höhle vor der Stadt.','De Lederer Zeff isch vomne mysteriöse Biescht inen Wolf verwandlet worde. Vilicht chan ich de Fluech breche, wenn ich das Ding umbring. Es versteckt sich inere Höhli vor de Stadt.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('cavern_beast','quest','The Cavern Beast','Das Höhlenmonster','Es Höhlemonster');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('cavern_beast', 'quest_desc','Inina gave me the task to kill the cavern beast that seems to be responsible for the missing people.','Inina gab mir den Auftrag, das Höhlenmonster zu töten, das anscheinend für die verschwundenen Leute verantwortlich ist.','D''Inina het mer de Uftrag ge, es Höhlemonster z''töte, wo anschiinend für di verschwundene Lüüt verantwortlich isch.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('hungry_wolf','quest','The Hungry Wolf','Der Hungrige Wolf','De Hungrig Wolf');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('hungry_wolf', 'quest_desc','Zeff is hungry as a wolf. To convince him that he will not take another sheep from the farmers, I should bring him some meat.','Zeff ist hungrig wie ein Wolf. Damit ich ihn überzeugen kann, keine Schafe mehr zu holen, sollte ich ihm etwas Fleisch bringen.','De Zeff isch hungrig we en Wolf. Zum ihn überzüüge, daser ke Schöfli me vode Buure holt, söti ihm chli Fleisch bringe.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('missing_paladin','quest','The Missing Paladin','Der Vermisste Paladin','De Vermisst Paladin');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('missing_paladin', 'quest_desc','Inina has sent a the Paladin Marcus into the caves behind the shrine. As he has not returned until now, I should check what happened to him. He is wearing Inina''s shining pendant, so it has to be easy to find him.','Inina hat den Paladin Marcus in die Höhlen hinter dem Schrein gesandt. Ich sollte nachsehen, was mit ihm passiert ist, da er noch nicht zurückgekehrt ist. Er trägt Ininas leuchtender Anhänger, daran sollte ich ihn erkennen.','Inina het de Paladin Marcus id Höhle hinter em Schrein gschickt. Ich söt naluege, was mit ihm passiert isch, well er isch nanig zrugg cho. Er het de Inina ihren lüchtende Ahänger ah, a dem söti ihn erkenne.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('clerics_recommendation','quest','The Letter of Recommendation','Das Empfehlungsschreiben','Es Empfehligsschriibe');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('clerics_recommendation', 'quest_desc','Inina gave me a letter of recommendation. With this paper I should get past the city guards and bring it to Commander Lloyd as soon as I''m in Gandria.','Inina hat mir ein Empfehlungschreiben gegeben. Mit diesem Stück Papier sollte es ein leichtes sein, an den Stadtwachen vorbeizukommen und in die Stadt zu gelangen. Wenn ich dort bin, soll ich den Brief Kommandant Lloyd bringen.','D''Inina het mer es Empfehligsschriibe gä mit dem ich ade Wache verbii id Stadt chum. Wenn ich in Gandria bi, söti de Brief zum Kommandant Lloyd bringe.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('zeff_returns','quest','A Wolf in the City','Ein Wolf in der Stadt','En Wolf ide Stadt');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('zeff_returns', 'quest_desc','Zeff''s curse is not broken but stopped. I need to convince the city guards to let him back in.','Zeffs Fluch ist zwar nicht gebrochen, aber gestoppt. Ich muss die Stadtwachen davon überzeugen, ihn wieder hineinzulassen.','Em Zeff sin Fluech isch zwar nid broche, aber gstoppt. Ich mun d''Stadtwache devo überzüüge, ihn wider iez''lah.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('zeff_returns', 'quest_desc_1','The city guards are informed and will let Zeff back into the city.','Die Stadtwachen sind informiert und werden Zeff in die Stadt zurückkehren lassen.','D''Stadtwache sind informiert und werded de Zeff zrugg id Stadt ga lah.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('broken_staff','quest','The Broken Staff','Der Zerbrochene Stab','De Verbroche Stab');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('broken_staff', 'quest_desc','If I collect all parts of this weapon, the blacksmith Harek should be able to fix it for me.', 'Wenn ich alle Stücke dieser Waffe finde, sollte sie der Schmied Harek wieder zusammensetzen können.','Wenn ich alli Teil vo dere Waffe finde, sött si de Schmied Harek wider zemesetze chöne.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ice_armor','quest','A Magic-Infused Armour','Eine Magie-Infundierte Rüstung','E Magie-Infundierti Rüstug');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('ice_armor', 'quest_desc','Harek agreed to smith a special armour for me, using the Heart of Khajag. I only need to bring him some iron ore from the mines of Gandria.', 'Harek wird eine spezielle Rüstung aus dem Herz von Khajag für mich schmieden, wenn ich ihm noch etwas Eisenerz aus den Minen von Gandria bringe.','De Harek wird e spezielli Rüstig usem Herz vom Khajag für mich schmide, wenn ich ihm na chli Iseerz us de Mine vo Gandria bring.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('elder_chest','quest','The Tear Stone','Der Tränenstein','De Tränestei');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('elder_chest', 'quest_desc','Vincent gave me the key to the Elder''s treasure chest. I have to get him a blue stone that''s inside and keep the rest. The treasure chest is in a secret room in the Elder''s house. I should make sure that the observer spells won''t catch me.', 'Vincent gab mir den Schlüssel zur Schatztruhe des Dorfältesten. Ich soll ihm einen blauen Stein aus der Kiste holen und den Rest für mich selbst behalten. Die Schatzkiste ist in einem Geheimraum im Haus des Dorfältesten. Ich sollte aufpassen, dass mich die Beobachter-Zauber nicht erwischen.','De Vincent het mer de Schlüssel zude Schatztrue vom Dorfälteste gä. Ich söt ihm en blaue Stei us de Chiste hole und cha de Rest für mich selber phalte. D''Schatzchiste isch imne Gheimruum im Huus vom Älteste. Ich söt ufpasse, dass mich d''Beobachter-Zauber nid verwütsched.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('stephens_helmet','quest','Stephen''s Helmet','Stephen''s Helm','Em Stephen sin Helm');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('stephens_helmet', 'quest_desc','The paladin Stephen wants me to get his helmet back. He lost it to some shady guys in the tavern in Gandria.', 'Der Paladin Stephen will, dass ich ihm seinen Helm zurück bringe. Er hat ihn an ein paar zwielichtige Gestalten in der Taverne verloren.','De Paladin Stephen wett dass ich ihm sin Helm zrugg bring. Er heten a paar komischi Gstalte im Wirtshuus vo Gandria verlore.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('stephens_helmet', 'quest_desc_1','The mercenary Jeremy told me that they lost the helmet somewhere in the sewers.','Der Söldner Jeremy hat mir gesagt, dass sie den Helm irgendwo in der Kanalisation verloren haben.','De Söldner Jeremy het mer gseit dass si de Helm irgendwo ide Kanalisation verlore hend.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('a_new_trace','quest','A New Trace','Eine neue Spur','E neui Spur');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('a_new_trace', 'quest_desc','I''ve got my old travel bag back. There is still some of my stuff inside, maybe that will help me to find out more about my lost memories.','Ich habe meinen alten Reiserucksack wieder. Er hat immer noch einige meiner alten Sachen drin. Vielleicht helfen mir diese, mehr über das, was ich vergessen habe, herauszufinden.','Ich ha min alte Reiserucksack wider. Er het immerna es paar vo mine alte Sache drin. Vilicht helfed mer die, chli me über das, woni vergesse ha, usezfinde.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('a_new_trace', 'quest_desc_1','The letter from the Elementalists says something about a mage named Jonathan who lives in Gandria. I should definitely see him.','Im Brief der Elementarmagier steht etwas von einem Magier Jonathan, den ich in der Stadt Gandria aufsuchen soll.','Im Brief vode Elementarmagier staht öppis vomne Magier Jonathan, wo ich in Gandria es Bsüechli abstatte söl.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('essence_of_fire','quest','The Essence of Fire','Die Essenz des Feuers','D''Füüressenz');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('essence_of_fire', 'quest_desc','The elementalist Jonathan wants me to collect essences of fire from the fire rats in his basement. If I bring him enough, he will teach me how to summon a fireball.', 'Der Elementarmagier Jonathan will, dass ich ihm Essenzen des Feuers von den Feuerratten in seinem Keller bringe. Wenn ich genügend sammle, lehrt er mich, wie man einen Feuerball beschwört.','De Elementarmagier Jonathan will, dass ich ihm Füüressenze vode Füürratte i sim Chäller bring. Wenni gnueg gsammlet ha, verzellt er mir, weme en Füürball beschwört.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('questionable_method','quest','A Questionable Method','Eine Fragwürdige Methode','E Frogwürdigi Methode');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('questionable_method', 'quest_desc','The alchemist Syrah can try to remove or weaken my curse if I bring her some ingredients from the sewers of Gandria.', 'Die Alchemistin Syrah kann meinen Fluch aufheben oder schwächen wenn ich ihr ein paar Zutaten aus der Kanalisation von Gandria bringe.','D''Alchemistin Syrah cha min Fluech ufhebe oder schwäche weni ire es paar Zuetate us de Kanalisation vo Gandria hol.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('join_a_guild','quest','Guilds of Gandria','Gilden von Gandria','Gilde vo Gandria');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('join_a_guild', 'quest_desc','I need to join a guild and learn their magic in order to help Jonathan with the enchanted map.', 'Ich muss einer Gilde beitreten und ihre Magie lernen um Jonathan mit der verzauberten Karte zu helfen.','Ich mun enere Gilde biitrette und iri Magie lerne zum em Jonathan mit de verzauberete Charte z''helfe.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('join_a_guild', 'quest_desc_1','The alchemist Syrah apperently knows some people that practice necromancy.','Die Alchemistin Syrah hat anscheinend Kontakte zu Nekromanten.','D''Alchemistin Syrah het anschiinend Kontäkt zu Nekromante.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('join_a_guild', 'quest_desc_2','Mages who practice twilight magic are mostly thieves and they like to hide in the underground.','Magier, die sich mit Dämmerungsmagie beschäftigen sind  meist Diebe und die verstecken sich gern im Untergrund.','Magier wo sich mit Dämmerigsmagie beschäftiged sind meistens Dieb und die verstecked sich gern im Untergrund.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('join_a_guild', 'quest_desc_3','It should be easy to join the Clerics, they''re always looking for new promising members.','Es sollte einfach sein, den Klerikern beizutreten, sie sind immer auf der Suche nach neuen vielversprechenden Mitgliedern.','Es söt ke Sach si, de Kleriker biiztrette, si sind immer uf de Suechi nach neue vielversprechende Mitglieder.');

INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('invis_recipe','quest','The Stolen Recipe','Das gestohlene Rezept','Es klaute Rezept');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('invis_recipe', 'quest_desc','I need to steal a recipe for an invisibility potion from the basement of the mage Syrah. There must be a way using the sewers to get there.','Ich muss ein Rezept für einen Unsichtbarkeitstrank aus dem Keller der Magierin Syrah stehlen. Über die Kanalisation sollte ich irgendwie in ihren Keller gelangen.', 'Ich mun es Rezept für en Unsichtbarkeitstrank usem Chäller vode Magierin Syrah chlaue. Über d''Kanalisation söti irgendwie det ane cho.');