INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_edmond','npc','Edmond','Edmond','Edmond');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_ingrid','npc','Ingrid','Ingrid','Ingrid');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_rhendal','npc','Elder Rhendal','Ältester Rhendal','Älteste Rhendal');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_innkeeper','npc','Innkeeper','Wirt','Wirt');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_vincent','npc','Vincent','Vincent','Vincent');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_thea','npc','Thea','Thea','Thea');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_andrew','npc','Andrew','Andrew','Andrew');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_inina','npc','High Priestess Inina','Hohepriesterin Inina','Hohepriesterin Inina');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_paladin1','npc','Paladin','Paladin','Paladin');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_paladin2','npc','Paladin','Paladin','Paladin');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_sheep1','npc','Sheep','Schaf','Schöfli');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_sheep2','npc','Sheep','Schaf','Schöfli');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_ivo','npc','Ivo','Ivo','Ivo');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_tristan','npc','Tristan','Tristan','Tristan');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_zeff','npc','Zeff','Zeff','Zeff');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_cityguard1','npc','City Guard','Stadtwache','Stadtwach');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('npc_cityguard2','npc','City Guard','Stadtwache','Stadtwach');