INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Press', 'hint','Press','Drücke die Taste','Druck d''Taste');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Journal', 'hint','to open the journal','um das Tagebuch zu öffnen','zums Tagebuech ufmache');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Inventory', 'hint','to open the inventory','um das Inventar zu öffnen','zums Inventar ufmache');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Chop', 'hint','to chop with your weapon','um mit deiner Waffe zu schlagen','zum mit dinere Waffe haue');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('LeaveLevel', 'hint','when standing at a level exit to leave the level','wenn du bei einem Level-Ausgang stehst, um das Level zu verlassen','wenn du vor emne Level-Usgang stahsch zum use gah');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Scout', 'hint','to scout','um einen besseren Überblick zu bekommen.','zum en bessere Überblick z''ha');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Map', 'hint','to open the map.','um die Karte zu öffnen.','zum d''Charte ufmache');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('MapMove', 'hint','to move.','um dich zu bewegen.','zum dich bewege.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Pickup', 'hint','Click on an item with the right mouse key to pickup.','Klicke einen Gegenstand mit der rechten Maustaste an, um ihn aufzuheben.','Klick en Gegestand mit de rechte Muustaschte ah zum ihn neh.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Highlight', 'hint','to highlight items that can be picked up.','um aufhebbare Gegenstände zu markieren.','zum ufhebbari Gegeständ markiere.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Reload', 'hint','Press the Escape key to go back to a previous checkpoint and reload the level.','Drücke Escape um zu einem vorherigen Kontrollpunkt zu gehen und das Level neu zu laden.','Druck Escape zum zumne vorherige Checkpoint zrugg z''ga und es Level neu z''lade.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Spellbook', 'hint','to open up the spellbook and equip your new spell.','um das Zauberbuch zu öffnen und deinen neuen Zauber auszurüsten.','zum es Zauberbuech ufmache und din neue Zauber uusz''rüste');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Checkpoint', 'hint','Activating a checkpoint with a right or left click will allow you to save your game and return to its position when you die.','Das Spiel kann an einem Kontrollpunkt gespeichert werden indem du ihn mit einem Links- oder Rechtsklick aktivierst. Du kannst dich dorthin zurückversetzen, falls du stirbst.','Es Spiel cha amne Checkpoint gspeicheret werde wenn du ihn mitme Links- oder Rechtsklick aktiviersch und du chasch det ane zrugg ga falls du verrecksch.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('Modifier', 'hint','Magical gems alter your spells. You can equip them outside of a level using your spellbook.','Magische Edelsteine verändern deine Zauber. Du kannst sie im Zauberbuch ausserhalb eines Levels ausrüsten','Magischi Edelset verändered dini Zauber. Du chasch si im Zauberbuech usserhalb vomne Level usrüste.');

