INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Active','Active','Aktiv','Aktiv','Activa');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('AdditionalResistance','Additional Resistance','Zusätzlicher Widerstand','Zuesätzliche Widerstand','Resistencia adicional');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('AllowedModifiers','Allowed Gem Types','Erlaubte Edelsteintypen','Erlaubti Edelsteitype','Tipo de gemas permitidas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Apply','Apply','Anwenden','Awende','Aplicar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('And','and','und','und','y');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Armor','Armour','Rüstung','Rüschtig','Armadura');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Autotarget','Auto Target','Automatisches Zielen','Automatisches Ziele','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('AutotargetOn','Auto target on','Automatisches Zielen an','Automatisches Ziele aa','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('AutotargetOff','Auto target off','Automatisches Zielen aus','Automatisches Ziele uus','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Back','Back','Zurück','Zrugg','Regresar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('BackToCheckpoint','Back to checkpoint','Zurück zum Kontrollpunkt','Zrugg zum Checkpoint','Regresar al punto de control');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('BackToMap','Leave level','Level verlassen','Usem Level gah','Salir del nivel');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('BackToMenu','Menu','Menu','Menu','Menú');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Book','Book','Buch','Buech','Libro');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Cancel','Cancel','Abbrechen','Abbreche','Cancelar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('CannotEquipInLevel','You cannot equip items inside a boss level!','Gegenstände können nicht in einem Bosslevel ausgerüstet werden!','Gegeständ chönd nid imne Bosslevel agleit werde!','¡No puede equipar objetos dentro del nivel boss!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('CannotConsumeItemInMap','You cannot consume food items on a map!','Verzehrbare Gegenstände können nicht auf einer Karte verwendet werden!','Ässbari Gegeständ chönd nid ufere Charte verbruucht werde!','¡No puedes consumir objetos alimento en el mapa!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('CharacterInfo','Character Info','Charakter Info','Charakter Info','Información de personaje');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Checkpoint','Checkpoint','Kontrollpunkt','Checkpoint','Punto de control');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('CheckpointReached','Checkpoint reached','Kontrollpunkt erreicht','Checkpoint erreicht','Punto de control alcanzado');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Chest','Chest','Truhe','Chischte','Cofre');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Chop','Chop','Hauen','Haue','Pegar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ClickToTeleport','Click to teleport','Klicken zum Teleportieren','Klicke zum Teleportiere','Clic para teletransportar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Completed','Completed','Fertig','Fertig','Completada');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ConfigurationSaved','Configuration was saved.','Einstellungen wurden erfolgreich gespeichert. ','Iistellige sind erfolgriich gspeicheret.','Configuración guardada.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Confirm','Confirm','Bestätigen','Bestätige','Confirmar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Consumables','Consumables','Tränke und Nahrung','Tränk und Ässe','Consumibles');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Consumed','consumed:','verbraucht:','verbruucht:','utilizado:');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Cooldown','Cooldown','Abklingzeit','Abklingziit','Enfriamiento');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('CooldownReduction','Cooldown Reduction','Abklingzeitverringerung','Abklingziitverringering','Reducción de enfriamiento');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Count','Count','Anzahl','Aazahl','Conteo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Credits','Credits','Mitwirkende','Credits','Créditos');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Critical','Critical','Kritisch','Kritisch','Crítico');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('CriticalHitChance','Critical Hit Chance','Kritische Trefferchance','Kritischi Trefferchance','Chance de golpe crítico');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Damage','Damage','Schaden','Schade','Daño');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DamageType','Damage Type','Schadenstyp','Schadetyp','Tipo de daño');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DamagePerSecond','Damage per Second','Schaden pro Sekunde','Schade pro Sekunde','Daño por segundo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Default','Default','Standardwert','Standardwert','Predeterminado');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Delete','Delete','Löschen','Lösche','Borar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DisplayMode','Display Mode','Anzeigemodus','Aazeigemodus','Modo de pantalla');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DialogueEnd','[END]','[ENDE]','[FERTIG]','[TERMINAR]');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DialogueTrade','[TRADE]','[HANDELN]','[HANDLE]','[COMERCIAR]');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DisplayDamageNumbers','Display Damage Numbers','Schadensszahlen anzeigen','Schadensszahle aazeige','Mostrar número de daños');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('DisplayHints','Display Hints','Tipps anzeigen','Tipps aazeige','Mostrar pistas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Divine','Divine','Heilig','Heilig','Divino');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Documents','Documents','Schriftstücke','Dokument','Documentos');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Done','Done','Erfüllt','Erfüllt','Terminada');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Door','Door','Tür','Türe','Puerta');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Duration','Duration','Dauer','Duur','Duración');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Elemental','Elemental','Elementar','Elementar','Elemental');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('English','English','Englisch','Englisch','Inglés');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EqBack','Back','Rücken','Rugge','Espalda');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EqBody','Chest','Brust','Bruscht','Pecho');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EqHead','Head','Kopf','Chopf','Cabeza');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EqNeck','Neck','Hals','Hals','Cuello');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EqRing','Finger','Finger','Finger','Dedo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EqWeapon','Weapon','Waffe','Waffe','Arma');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Equipment','Equipment','Ausrüstung','Usrüschtig','Equipo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EquipWeapon','Equip a weapon with spell slots to use spells.','Rüste eine Waffe mit Zauber-Slots aus, um Zauber einzusetzen.','Leg e Waffe mit Zauber-Slots ah zum Zauber iisetze.','Equipa un arma con ranura de hechizo para usar hechizos.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Empty','Empty','Leer','Läär','Vacío');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('EmptySlot','Empty slot','Leerer Platz','Lääre Platz','Ranura vacía');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Exit','Exit','Beenden','Beende','Salir');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Failed','Failed','Gescheitert','Gfailt','Fallida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FearLevel','Fear Strength','Furchtstärke','Angschtstärchi','Fuerza de temor');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('StunLevel','Stun Strength','Betäubungsstärke','Betäubigsstärchi','Fuerza de aturdimiento');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FifthSpell','5. Spell','5. Zauber','5. Zauber','5. Hechizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FireDamage','Fire Damage','Feuerschaden','Füürschade','Daño de fuego');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FireResistance','Fire Resistance','Feuerresistenz','Füürresistenz','Resistencia al fuego');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FirstSpell','1. Spell','1. Zauber','1. Zauber','1. Hechizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FourthSpell','4. Spell','4. Zauber','4. Zauber','4. Hechizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('FocusCrystal','Focusing Crystal','Fokus-Kristall','Fokus-Kristall','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Fullscreen','Fullscreen','Vollbild','Vollbild','Pantalla completa');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GameSaved','Game saved','Spiel gespeichert','Spiel gspeicheret','Partida guardada');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Gems','Gems','Edelsteine','Edelstei','Gemas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GemSockets','Gem Sockets','Edelstein Sockel','Edelstei Sockel','Cuencas para gemas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GemSocket','Gem Socket','Edelstein Sockel','Edelstei Sockel','Cuenca para gemas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('German','German','Deutsch','Düütsch','Alemán');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GodmodeActivated','Godmode activated','Godmode aktiviert','Godmode aktiviert','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GodmodeDeactivated','Godmode deactivated','Godmode deaktiviert','Godmode deaktiviert','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Gold','Gold','Gold','Gold','Oro');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GoldValue','Gold Value','Goldwert','Goldwert','Valor en oro');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Guild','Guild','Gilde','Gilde','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GuildJoined','Guild joined','Gilde beigetreten','Gilde biitrette','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoGuild','No Guild','Keine Gilde','Kei Gilde','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Haste','Haste','Schnelligkeit','Schnelligkeit','Agilidad');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Heal','Healing Power','Heilkraft','Heilchraft','Sanar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Health','Health','Lebensenergie','Lebe','Salud');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('HealthRegeneration','Health Regeneration','Lebensregeneration','Lebensregeneration','Regeneración de salud');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('HealthRegenerationPerS','Health Regeneration / s','Lebensregeneration / s','Lebensregeneration / s','Regeneración de salud / s');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Hint','Hint','Tipp','Tipp','Pista');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Hints','Hints','Tipps','Tipps','Pistas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('HolyPower','Holy Power','Heilige Kraft','Heiligi Chraft','Poder Divino');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IceDamage','Ice Damage','Eisschaden','Iisschade','Daño de hielo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IceResistance','Ice Resistance','Eisresistenz','Iisresistenz','Resistencia al hielo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Immune','Immune','Immun','Immun','Inmune');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Interact','Interact','Interagieren','Interagiere','Interactuar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Inventory','Inventory','Inventar','Inventar','Inventario');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IsLocked','Is locked!','Ist verschlossen!','Da isch abgschlosse!','¡Está cerrado!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IsLockedKey','Is locked! (Key needed)','Ist verschlossen! (Schlüssel benötigt)','Da isch abgschlosse! (Brucht en Schlüssel)','¡Está cerrado!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IsLockedOneway','Does not open from this side!','Lässt sich von dieser Seite nicht öffnen!','Chame vo dere Siite nid ufmache!','¡Está cerrado!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IsLockedPicklock','Is locked! (Picklock needed)','Ist verschlossen! (Dietrich benötigt)','Da isch abgschlosse! (Brucht en Dietrich)','¡Está cerrado!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('IsLockedKeyPicklock','Is locked! (Key/Picklock needed)','Ist verschlossen! (Schlüssel/Dietrich benötigt)','Da isch abgschlosse! (Brucht en Schlüssel/Dietrich)','¡Está cerrado!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Journal','Journal','Tagebuch','Tagebuech','Diario');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Jump','Jump','Springen','Springe','Saltar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('KeyBindings','Key Bindings','Tastaturbelegung','Tastaturbelegig','Teclas configurables');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('KeyBindingsShort','Key Bindings','Tastaturbelegung','Tastaturbelegig','Teclas config.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('KeyReserved','This key is reserved and cannot be selected.','Diese Taste ist reserviert und kann nicht gewählt werden.','Die Taste isch reserviert und derf me nid bruche.','Tecla en uso. No puede ser seleccionada.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Keys','Keys','Schlüssel','Schlüssel','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Killed','Killed','Getötet','Killt','Asesinado');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Feared','Feared','Verängstigt','Verängstigt','Asustado');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Stunned','Stunned','Betäubt','Betäubt','Aturdido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GargoyleStrength','Gargoyle Strength','Gargoyle-Stärke','Gargoyle-Stärchi','Fuerza gargólica');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Language','Language','Sprache','Sproch','Idioma');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Level','Level','Stufe','Level','Nivel');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Lever','Lever','Hebel','Hebel','Palanca');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('LightDamage','Light Damage','Lichtschaden','Liechtschade','Daño de luz');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('LightResistance','Light Resistance','Lichtresistenz','Liechtresistenz','Resistencia a la luz');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('LimitFPS','Limit FPS','FPS limitieren','FPS limitiere','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Load','Load','Laden','Lade','Cargar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('LoadGame','Load Game','Spiel laden','Spiel lade','Cargar partida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('LockpickLevel','Lockpick Level','Dietrich Stufe','Dietrich Level','Nivel de ganzúa');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Map','Map','Karte','Charte','Mapa');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MaxFPS','Max. FPS','Max. FPS','Max. FPS','FPS máximos');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MaxHealthPoints','Max. Health','Max. Lebensenergie','Max. Lebensenergie','Salud máxima');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MessageNewSaveGame','Please enter the name for your new saved game (at most 24 characters).','Bitte gib einen Namen ein für deinen neuen Speicherstand (höchstens 24 Zeichen).','Bitte gib en Name ih für din neue Speicherstand (höchstens 24 Zeiche).','Favor introduzca el nombre para su nueva partida guardada (máximo 24 caracteres).');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Meta','Meta','Meta','Meta','Meta');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Miscellaneous','Miscellaneous','Plunder','Grümpel','Otros');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ModifierLearned','Gem learned','Edelstein erlernt','Edelstei glernt','Gema aprendida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLearned','Spell learned','Zauber erlernt','Zauber glernt','Hechizo aprendido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MoveDown','Move down','Nach unten bewegen','Abelaufe','Bajar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MoveLeft','Move left','Nach links laufen','Links laufe','Ir a la izquierda');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MoveRight','Move right','Nach rechts bewegen','Rechts laufe','Ir a la derecha');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MoveUp','Move up','Nach oben bewegen','Uelaufe','Subir');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Necromancy','Necromancy','Nekromantie','Nekromantie','Necromancia');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NeedPickaxe','You need a pickaxe to mine ore.','Du brauchst eine Spitzhacke um Erz abzubauen.', 'Du bruchsch en Pickel zum Erz hacke.','Necesitas una piqueta para minar minerales.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NeedPortstone','You need a teleporter stone to teleport.','Du brauchst einen Teleportstein um dich zu teleportieren.', 'Du bruchsch en Teleportstei zum dich teleportiere.','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('New','New','Neu','Neu','Nuevo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NewGame','New Game','Neues Spiel','Neus Spiel','Nueva partida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NewJournalEntry','New journal entry','Neuer Tagebucheintrag','Neue Tagebuechiitrag','Nueva entrada en el diario');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('No','No','Nein','Nai','No');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoQuicksaveExists','No quick save exists','Kein Schnelllade-Speicherstand existiert','Kein Schnelllade-Speicherstand existiert','No existe guardado rápido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NotEnoughGold','Not enough gold!','Nicht genügend Gold!','Nid gnueg Gold!','¡No hay suficiente oro!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NotEnoughMaterials','Not enough materials!','Nicht genügend Materialien!','Nid gnueg Mats!','¡No hay suficiente ?!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NotEnoughStrength','The spell is not strong enough!','Der Zauber ist nicht genügend stark!','De Zauber isch nid gnueg starch!','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NotEnoughReputation','Not enough reputation!','Nicht genügend Ruf!','Nid gnueg Ruef!','¡No hay suficiente reputación!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NothingToGain','Nothing to gain there anymore.','Da ist nichts mehr zu holen.', 'Da gits nüt me z''hole.','Nada que minar.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NothingToSay','There''s nothing to talk about.','Es gibt nichts zu sagen.','Es git nüt zum rede.','No hay de qué hablar.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoWeapon','No weapon','Keine Waffe','Kei Waffe','Sin arma');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoSpells','No spells learned.','Keine Zauber gelernt.','Kei Zauber glernt.','Sin hechizos aprendidos.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoQuests','No quests found.','Keine Quests gefunden.','Kei Quests gfunde.','Sin misiones encontradas.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoHints','No hints learned.','Keine Tipps gelernt.','Kei Tipps glernt.','Sin pistas aprendidas.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NoSaves','No saves found.','Kein Speicherstand gefunden.','Kein Speicherstand gfunde.','No hay partidas guardadas.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Observed','Observed','Beobachtet','Beobachtet','Observado');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Off','Off','Aus','Uus','Apagar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Okay','Okay','Okay','Okee','Aceptar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('On','On','An','Ii','Encendido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('OperationFailed','Operation failed.','Operation fehlgeschlagen.','Die Operation isch id Hose.','Operación fallida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Options','Options','Einstellungen','Iistellige','Opciones');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Ore','Ore','Erz','Erz','Minerales');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('OutOfRange','Out of range','Ich muss näher ran','Da isch z''wiit weg','Fuera de rango');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Pending','Pending','Ausstehend','Nanig erfüllt','Pendiente');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Permanent','Permanent','Permanent','Permanent','Permanente');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('PhysicalDamage','Physical Damage','Physischer Schaden','Physische Schade','Daño físico');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('PressAnyKey','<?>','<?>','<?>','<?>');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Price','Price','Preis','Priis','Precio');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Quest','Quest','Quest','Quest','Misión');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('QuestionDeleteSaveGame','Do you really want to delete this save game?','Willst du diesen Speicherstand wirklich löschen?','Wetsch de Speicherstand würkli lösche?','¿Realmente quieres eliminar la partida guardada?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('QuestionLoadGame','Load game?
All unsaved progress will be lost.','Spiel laden?
Ungespeicherter Fortschritt geht verloren.','Spiel lade?
Ungspeicherete Fortschritt isch futsch.','¿Cargar partida?
Todo progreso sin guardar se perderá.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('QuestionOverwriteSaveGame','Overwrite this save game?','Diesen Speicherstand überschreiben?','De Speicherstand überschribe?','¿Sobrescribir esta partida guardada?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('QuestionStartNewGame','Start new game?
All unsaved progress will be lost.','Neues Spiel starten?
Ungespeicherter Fortschritt geht verloren.','Neus Spiel starte?
Ungspeicherete Fortschritt isch futsch.','¿Iniciar nueva partida?
Todo proceso sin guardar se perderá.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('QuestItems','Quest Items','Questgegenstände','Questgegeständ','Objetos de misión');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Quickcast','Quickcast','Schnellzaubern','Schnellzaubere','Conjuración rápida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Quickload','Quick Load','Schnell Laden','Schnell Lade','Cargado rápido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Quicksave','Quick Save','Schnell Speichern','Schnell Speichere','Guardado rápido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Quickslot1','Quick Slot 1','Schnellwahl 1','Schnellwahl 1','Acceso rápido 1');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Quickslot2','Quick Slot 2','Schnellwahl 2','Schnellwahl 2','Acceso rápido 2');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Range','Range','Reichweite','Riichwiiti','Rango');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Reduction','Reduction','Verminderung','Verminderig','Reducción');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Reflection','Reflection','Reflektion','Abpraller','Reflexión');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Reputation','Reputation','Ruf','Ruef','Reputación');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Reset','Reset','Zurücksetzen','Zruggsetze','Reiniciar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Resume','Resume','Spiel fortsetzen','Zrugg zum Spiel','Continuar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('RightClickOpen','Right click to open','Rechtsklicken zum Öffnen','Rechtsklicke zum ufmache','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('RightClickLearn','Right click to learn','Rechtsklicken zum Lernen','Rechtsklicke zum lerne','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('RightClickRead','Right click to read','Rechtsklicken zum Lesen','Rechtsklicke zum läse','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Save','Save','Speichern','Speichere','Guardar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SaveGame','Save Game','Spiel speichern','Spiel speichere','Guardar partida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SavegameDeleted','Save game successfully deleted.','Speicherstand erfolgreich gelöscht.','Speicherstand isch glöscht.','Partida guardada eliminada satisfactoriamente.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Screenshot','Screenshot','Bildschirmfoto','Bildschirmföteli','Captura de pantalla');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SecondSpell','2. Spell','2. Zauber','2. Zauber','2. Hechizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ShadowDamage','Shadow Damage','Schattenschaden','Schatteschade','Daño de sombra');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ShadowResistance','Shadow Resistance','Schattenresistenz','Schatteresistenz','Resistencia a sombra');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Smoothing','Texture Smoothing','Texturen glätten','Texture glätte','Suavizado de textura');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Sound','Sound','Musik','Musig','Sonido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SoundVolume','Sound Volume','Lautstärke Effekte','Effekt-Luutstärchi','Volumen de sonido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('MusicVolume','Music Volume','Lautstärke Musik','Musig-Luutstärchi','Volumen de música');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Speed','Speed','Geschwindigkeit','Gschwindigkeit','Velocidad');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellAntiGravity','Anti Gravity','Schwerkraft umkehren','Schwerchraft umchere','Antigravedad');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellAntiGravityDesc','Reverses gravity for Cendric for a certain duration.','Dreht Cendrics Schwerkraft für eine gewisse Zeit um.','Drüllt em Cendric sini Schwerchraft für e gwüssi Ziit um.','Invierte la gravedad de Cendric por cierto tiempo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellAureola','Aureola','Strahlenkranz','Strahlechranz','Aureola');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellAureolaDesc','Sends balls of light in all directions, if they hit an enemy they will return to Cendric and heal him.','Schickt Lichtbälle in alle Richtungen, die zurückkehren und Cendric heilen, falls sie einen Gegner treffen.','Schickt Liechtbäll in all Richtige, wo zruggchömed und de Cendric heiled wenn si en Gegner troffe hend.','Arroja esferas de luz en todas direcciones. Si golpean a un enemigo, regresan a Cendric y lo curan.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Spellbook','Spellbook','Zauberbuch','Zauberbuech','Libro de hechizos');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellDivineShield','Divine Shield','Göttlicher Schild','Göttlichs Schild','Escudo divino');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellDivineShieldDesc','Grants a shield that enhances Cendrics resistances and heals him once.','Umhüllt Cendric mit einem Schild, der ihn einmalig heilt und für eine gewisse Dauer seine Resistenzen erhöht.','Umhüllt de Cendric mitme Schild wo ihn eimalig heilt und sini Resistenze für e gwüssi Ziit erhöht.','Otorga un escudo que aumenta la resistencias de Cendric y lo cura una vez.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellFear','Fear','Furcht','Angscht','Temor');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellFearDesc','Enemies will flee in terror for a certain duration if the spell is strong enough.','Gegner fliehen für eine gewisse Zeit, allerdings nur, wenn der Zauber genug stark für sie ist.','Gegner flüchtet für e gwüssi Ziit, aber nur, wenn de Zauber gnueg starch isch für si.','Si el hechizo es suficientemente fuerte, los enemigos huirán aterrorizados por un lapso de tiempo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellFireBall','Fireball','Feuerball','Füürball','Bola de fuego');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellFireBallDesc','The good old fireball. Burns enemies and melts ice.','Der gute alte Feuerball. Verbrennt Gegner und schmilzt Eis.','De guet alt Füürball. Verbrennt Gegner und schmelzt Iis.','La siempre leal bola de fuego. Quema enemigos y derrite el hielo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellIceBall','Iceball','Eisball','Iisball','Bola de hielo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellIceBallDesc','An icy ball damages enemies and freezes water.','Ein eisiger Ball schadet Gegnern und gefriert Wasser.','En iisige Ball schadet Gegner und gfrüürt Wasser.','Una bola gélida que daña enemigos y congela el agua.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellFlash','Flash','Blitz','Blitz','Relámpago');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellFlashDesc','Cendric dashes forward with speed of light, ignores most blocks and damages enemies.','Cendric schiesst mit Lichtgeschwindigkeit vorwärts, ignoriert die meisten Blöcke und schadet Gegner.','De Cendric schüsst mit Liechtgschwindigkeit vorwärts, ignoriert di meiste Blöck und schadet Gegner.','Cendric avanza a la velocidad de la luz, sobrepasa la mayoría de bloqueos y daña a los enemigos.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellIcyAmbush','Icy Ambush','Eisiger Hinterhalt','Iischalte Hinterhalt','Emboscada helada');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLight','Light','Licht','Liecht','Resplandor');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLightDesc','There shall be light!','Es werde Licht!','Chasch chli heller mache, bitte?','¡Hágase la luz!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellIcyAmbushDesc','Cendric throws an enchanted dagger that deals big damage when it hits an enemy, stuns it and enemies in range and teleports Cendric to its location.','Cendric wirft einen verzauberten Dolch, der eine grosse Menge Schaden verursacht, wenn er einen Gegner trifft und Cendric an dessen Stelle teleportiert. Gegner im Umkreis werden betäubt.','De Cendric wirft en verzauberte Dolch wo viel Schade amne Gegner macht und Gegner im Umkreis betäubt. De Cendric wird ad Stell vom troffene Gegner teleportiert.','Cendric lanza una daga encantada que hace gran daño cuando golpea a un enemigo, aturde a este y a los enemigos al alcance y lo teletransporta a su ubicación.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLeech','Leech','Lebensraub','Lebesraub','Sanguijuela');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLeechDesc','Sends out leeching spells that damage enemies and return to Cendric to heal him if they hit an enemy.','Schickt lebensraubende Zauber aus, die zu Cendric zurückkehren, um ihn zu heilen, falls sie einen Gegner getroffen haben.','Schickt lebensraubendi Zauber uus wo zum Cendric zruggchömed zum ihn heile falls si en Gegner troffe hend.','Envía hechizos de sanguijuelas que dañan a los enemigos y regresan a Cendric para curarlo cuando golpean a un enemigo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLeapOfFaith','Leap of Faith','Glaubenssprung','Glaubessprung','Salto de fe');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellLeapOfFaithDesc','A holy power flows through Cendric, enabling him to jump higher and fall slower for a certain duration.','Eine heilige Kraft durchströmt Cendric, die ihn höher springen und langsamer fallen lässt.','E heiligi Kraft durchströmt de Cendric, mit dere er höcher springe und langsamer falle chan.','Un poder divino fluye a través de Cendric, el cual le premite saltar más alto y caer más despacio por cierto tiempo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellShadowTrap','Shadow Trap','Schattenfalle','Schattefalle','Trampa de sombra');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellShadowTrapDesc','Cendric places a shadow trap on the ground that stuns enemies and deals damage over time when triggered.','Cendric platziert eine Schattenfalle am Boden, die Gegner betäubt und Schaden über Zeit verursacht, wenn sie ausgelöst wird.','De Cendric setzt e Schattefalle uf de Bode wo Gegner betäubt und Schade über Ziit macht wenn si usglöst wird.','Cendric coloca una trampa de sombra en el piso, la cual, al activarse, aturde a los enemigos y ocasiona daño por cierto tiempo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellRaiseTheDead','Raise The Dead','Tote Erwecken','Toti Erwecke','Resurreción de los muertos');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellRaiseTheDeadDesc','Raises fallen enemies that will fight for Cendric for a certain duration, if the spell is strong enough.','Erweckt gefallene Gegner wieder, die für eine gewisse Zeit für Cendric kämpfen, falls der Zauber genügend stark ist.','Erweckt toti Gegner wider und laht si für e gwüssi Ziit für de Cendric kämpfe, falls de Zauber gnueg starch isch.','Resucita enemigos caídos que lucharán por Cendric durante cierto tiempo, si el hechizo es suficientemente fuerte.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellHolyFire','Holy Fire','Heiliges Feuer','Heiligs Füür','Fuego divino');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellHolyFireDesc','Cendric summons a holy fire that burns enemies in range.','Cendric beschwört ein heiliges Feuer, das Gegner in der Nähe verbrennt.','De Cendric beschwört es heiligs Füür wo Gegner ide Nöchi verbrennt.','Cendric convoca a un fuego divino que quema a enemigos al alcance.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellSummonGargoyle','Summon Gargoyle','Gargoyle Beschwören','Gargoyle Beschwöre','Convocación de gárgola');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellSummonGargoyleDesc','Cendric summons a mighty gargoyle that serves him and attacks enemies.','Cendric beschwört einen mächtigen Gargoyle, der Gegner attackiert.','De Cendric beschwört en mächtige Gargoyle wo Gegner aagrift.','Cendric convoca una poderosa gárgola a su servicio y ataca enemigos.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellSlots','Spell Slots','Verfügbare Zauber','Verfüegbari Zauber','Espacios de hechizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellUnlock','Summon Picklock','Dietrich beschwören','Dietrich beschwöre','Convocación de ganzúa');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellUnlockDesc','Summons a picklock that is able to unlock locked chests if its strength is big enough for the chest.','Beschwört einen Dietrich, der verschlossene Truhen knackt, sofern die Stärke des Zaubers ausreicht.','Beschwört en Dietrich ane wo e verschlosseni Chischte knackt sofern de Zauber gnueg starch isch für die Chischte.','Convoca a una ganzúa que puede abrir cofres si es lo suficientemente fuerte para el cofre.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellWindGust','Wind Gust','Windstoss','Windstoss','Ráfaga de viento');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellWindGustDesc','A wind gust that is able to shift certain objects.','Ein Windstoss der gewisse Objekte verschieben kann.','En Windstoss wo gwüssi Objekt verschiebe chan.','Una ráfaga de viento capaz de mover ciertos objetos.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('StartGame','Start Game','Spiel starten','Spiel starte','Iniciar partida');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Stats','Stats','Statuswerte','Statuswert','Estadísticas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Strength','Strength','Stärke','Stärchi','Fuerza');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SwissGerman','Swiss German','Schweizerdeutsch','Schwiizerdüütsch','Alemán Suizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ThirdSpell','3. Spell','3. Zauber','3. Zauber','3. Hechizo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToggleTooltips','Toggle Tooltips','Tooltips anzeigen/verbergen','Tooltips zeige/verstecke','Alternar información de herramientas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToggleAutotarget','Toggle Autotarget','Automatisches Zielen an/aus','Automatisches Ziele aa/uus','Alternar ?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Twilight','Twilight','Zwielicht','Dämmerig','Crepúsculo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Type','Type','Typ','Typ','Tipo');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Unknown','Unknown','Unbekannt','Unbekannt','Desconocido');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Unsalable','Cannot be sold','Unverkäuflich','Unverchäuflich','No se puede vender');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Waypoint','Waypoint','Wegmarke','Wägpunkt','Coordenadas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('WaypointNotActive','Waypoint not active!','Wegmarke ist nicht aktiv!','De Wägpunkt isch nid aktiv!','¡Coordenadas no activadas!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('WaypointActivated','Waypoint activated','Wegmarke aktiviert','Wägpunkt aktiviert','Coordenadas activas');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('WeaponDamage','Weapon Damage','Waffenschaden','Waffeschade','Daño de arma');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('WindForce','Wind Force','Windstärke','Windstärchi','Fuerza viento');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Window','Window','Fenster','Fenster','Ventana');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('WindowedFullscreen','Full Window','Vollbild im Fenster','Vollbild im Fenster','Ventana completa');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Yes','Yes','Ja','Ja','Sí');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('VSync','Vsync','Vsync','Vsync','Sincronización vertical');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('GhostArmor','Ghost Armour','Geisterrüstung','Geisterrüschtig','Armadura fantasma');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ScreenshotSaved','Screenshot saved','Bildschirmfoto gespeichert','Bildschirmföteli gspeicheret','Captura de pantalla guardada');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Sign','Sign','Schild','Schild','Letrero');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Spanish','Spanish','Spanisch','Spanisch','Español');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellTelekinesis','Telekinesis','Telekinese','Telekinese','Telequinesis');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellTelekinesisDesc','What seemed to be far is now near.','Das, was unerreichbar schien, ist nun greifbar geworden.','Unerreichbar isch es Fremdwort worde.','Lo que parecía estar lejos, ahora está cerca.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellGhostForm','Ghost Form','Geistergestalt','Geistergstalt','Forma fantasma');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellGhostFormDesc','Cendric takes the shape of a ghost, making him able to walk through certain blocks, walk faster and gain additional armour.','Cendric nimmt eine Geisterform an, was ihn durch bestimmte Blöcke gehen lässt, ihn schneller macht und ihm zusätzliche Rüstung gewährt.','De Cendric nimmt e Geisterform ah, mit dere er dur gwüssi Blöck laufe cha, schneller lauft und me Rüschtig het.','Cendric adopta la forma de fantasma, lo que le permite caminar más rápido, atravesar ciertos obstáculos y ganar armadura adicional.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellInvisibility','Invisibility','Unsichtbarkeit','Unsichtbarkeit','Invisibilidad');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SpellInvisibilityDesc','Renders Cendric invisible for a certain duration for certain enemies','Cendric wird unsichtbar für eine gewisse Zeit und für gewisse Gegner.','Cendric wird unsichtbar für e gwüssi Ziit und gwüssi Gegner.','Hace invisible a Cendric ante algunos enemigos por cierto tiempo.');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToInteract','to interact','- interagieren','zum interagiere','para interactuar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('SwitchTarget','Switch target','Ziel wechseln','Ziel ändere','?');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToTalk','to talk','- reden','zum rede','para hablar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToCook','to cook','- kochen','zum choche','para cocinar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToPickup','to pickup','- aufnehmen','zum neh','para levantar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToLoot','to loot','- plündern','zum neh','para saquear');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToActivate','to activate','- aktivieren','zum aktiviere','para activar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToRead','to read','- lesen','zum läse','para leer');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToSwitch','to toggle','- umschalten','zum drucke','para alternar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToRotate','to rotate','- drehen','zum trülle','para girar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToSteal','to steal','- stehlen','zum chlaue','para robar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToOpen','to open','- öffnen', 'zum ufmache','para abrir');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('ToMine','to mine','- abbauen', 'zum abbaue','para minar');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('InvisibilityLevel','Transparency','Transparenz','Transparenz','Transparencia');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Fireplace','Fireplace','Kochstelle','Chochstell','Fogata');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('NothingToCook','[Nothing to cook...]','[Nichts zu kochen...]','[Es git nüt zum chochä...]','[Nada que cocinar...]');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('LeverStuck','The lever is stuck!','Der Hebel ist verklemmt!','De Hebel isch verchlemmt!','¡La palanca está atorada!');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('Used','Used ','Benutzt: ','Brucht: ','Usada ');
INSERT INTO text (text_id, english, german, swiss_german, spanish) values ('','','','','');