INSERT INTO users (user_id, name) values (1, 'Rahel');
INSERT INTO users (name) values ('André');
INSERT INTO users (name) values ('Dominic');
INSERT INTO users (name) values ('Cheshire Cat');
INSERT INTO users (name) values ('Tizian');
INSERT INTO users (name) values ('Pit');
INSERT INTO users (name) values ('Morgi');
INSERT INTO users (name) values ('Martin');
INSERT INTO users (name) values ('Üse');
INSERT INTO users (name) values ('Joey');
INSERT INTO users (name) values ('Alchemilla');
INSERT INTO users (name) values ('Haab');
INSERT INTO users (name) values ('Galli');
INSERT INTO users (name) values ('Mylan');
INSERT INTO users (name) values ('Dodi');
INSERT INTO users (name) values ('Christian');
INSERT INTO users (name) values ('Joli');
INSERT INTO users (name) values ('Emine');
INSERT INTO users (name) values ('Wenk');
INSERT INTO users (name) values ('Master (Rafi)');
INSERT INTO users (name) values ('Jonas');
INSERT INTO users (name) values ('Judith');
INSERT INTO users (name) values ('Dani');
INSERT INTO users (name) values ('Kübler');
INSERT INTO users (name) values ('Pädi');
INSERT INTO users (name) values ('Gabriel');
INSERT INTO users (name) values ('Enis');
INSERT INTO users (name) values ('Sascha');
INSERT INTO users (name) values ('Larissa');
INSERT INTO users (name) values ('Andrea');
INSERT INTO users (name) values ('Bernie');
INSERT INTO users (name) values ('Dani (Rahel''s)');
INSERT INTO users (name) values ('Lilli');
INSERT INTO users (name) values ('Mät');