#pragma once

enum class ResourceID
{
	Void,

	BitmapFont_default,
	Translations,
	Configuration,
	Quicksave,
	Save_folder,
	Items,
	Texture_mainChar,
	Texture_mapMainChar,
	Texture_spell_fire,
	Texture_spell_ice,
	Texture_spell_forcefield,
	Texture_spell_unlock,
	Texture_tile_ice,
	Texture_tile_crumblyblock,
	Texture_tile_torch,
	Texture_tile_chest,
	Texture_tile_spikestop,
	Texture_tile_spikesbottom,
	Texture_tile_frozenwater,
	Texture_screen_splash,
	Texture_screen_splash_fireanimation,
	Texture_screen_loading,
	Texture_screen_error_fileNotFound,
	Texture_screen_error_dataCorrupted,
	Texture_screen_gameover,
	Texture_screen_menu,
	Texture_screen_credits,
	Texture_enemy_rat,
	Texture_enemy_firerat,
	Texture_levelitems,
	Texture_items,
	Texture_npcs,
	Texture_dialogue,
	Texture_GUI_rounded_rectangle,
	Texture_GUI_ornament_none,
	Texture_GUI_ornament_small,
	Texture_GUI_ornament_medium,
	Texture_GUI_ornament_large,
};