#pragma once

enum class ResourceID
{
	Void,
	Map_testmap,
	Level_testlevel,
	Font_copperplateGothicBold,
	Texture_mainChar,
	Texture_mapMainChar,
	Texture_spell_fire,
	Texture_spell_ice,
	Texture_spell_forcefield,
	Texture_tile_water,
	Texture_tile_ice,
	Texture_tile_crumblyblock,
	Texture_weapon_icestaff,
	Texture_weapon_rustysword,
	Texture_head_wizardhat_grey,
	Texture_head_wizardhat_blue,
	Texture_screen_splash,
	Texture_screen_splash_fireanimation,
	Texture_screen_loading,
	Texture_screen_error_fileNotFound,
	Texture_screen_error_dataCorrupted,
	Texture_screen_menu,
	Texture_enemy_rat,
	Texture_enemy_firerat,
	Texture_levelitems,
	Texture_items,
};