INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhoAreYou', 'dl_npc_thiran', 'Who are you?', 'Wer bist du?', 'Wer bisch du?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Thiran_WhoAreYou', 'dl_npc_thiran', 'I''m Thiran, quartermaster of the clerics. What can I do for you?', 'Ich bin Thiran, Rüstmeister der Kleriker. Was kann ich für dich tun?', 'Ich bi de Thiran, de Rüstmeister vode Kleriker. Was chani für dich mache?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_Wares', 'dl_npc_thiran', 'Show me your wares.', 'Zeig mir deine Waren.', 'Wa hesch so im Agebot?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_Learn', 'dl_npc_thiran', 'Can you teach me some spells?', 'Kannst du mir Zauber beibringen?', 'Chasch du mir Zauber bibringe?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_SecondSpell', 'dl_npc_thiran', 'Can you teach me more spells?', 'Kannst du mir noch mehr Zauber beibringen?', 'Chasch mer na me Zauber bibringe?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Thiran_NoTeaching', 'dl_npc_thiran', 'No, I only share my knowledge with members of the order.', 'Nein, ich gebe mein Wissen nur an Mitglieder des Ordens weiter.', 'Nei, ich chan nur Lüt wo zum Orde ghöred öppis bibringe.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Thiran_YesTeachingFirst', 'dl_npc_thiran', 'Yes, as you''ve chosen the way of the Eternal Light, I can grant you access to its magic. Here, take this scroll and learn how to unleash the wrath of light.', 'Ja, da du den Weg des Ewigen Lichts eingeschlagen hast, kann ich dir Zugang zu seiner Magie gewähren. Hier, nimm diese Schriftrolle und lerne, wie man den Zorn des Lichts entfesselt.', 'Ja, well du de Weg vom Ewige Liecht igschlage hesch chani der sini Magie bibringe. Da, nimm die Schriftrolle und lern weme de Zorn vom Liecht entfesslet.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Thiran_NoFurtherSpell', 'dl_npc_thiran', 'Not yet. I''m going to teach you another spell when you''ve worked for us.', 'Noch nicht. Ich werde dir einen weiteren Zauber beibringen, wenn du für uns gearbeitet hast.', 'Nonid. Ich cha der en negste Zauber zeige wennd chli für üs gschaffet hesch.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Thiran_SecondSpell', 'dl_npc_thiran', 'Yes, you''ve proven yourself worthy to learn more divine magic. Here you go.', 'Ja, du hast dich als würdig erwiesen um mehr heilige Magie zu erlernen. Hier, nimm.', 'Ja, du hesch dich als würdig erwise zum me heiligi Magie lerne. Da, nimm.');
