INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Cendric_Okay', 'DL_Guard', 'Okay, I will do that.','Okay, das mache ich.','Okay, dännhalt.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_GiveMeAQuest', 'DL_Guard', 'Give me a quest.','Gib mir eine Aufgabe.','Gib mer was zum mache.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Nothing', 'DL_Guard', 'None of your business.','Geht dich nichts an.','Gaht dich en füechte Dreck ah.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_Hello', 'DL_Guard', 'Hey you, stop! What are you doing here, so very alone? It''s dangerous out here.','Hey du, stopp! Was machst du hier, so alleine? Es ist gefährlich hier draussen.','Hey du, stop! Was machsch du da? Es isch gföhrlich, so elei go umelaufe.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_KillSomeRats', 'DL_Guard', 'Okay, go and kill some rats for me.','Okay, dann geh und töte ein paar Ratten für mich.','Okay, dänn gang und kill es paar Ratte für mich.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_KillThemAlready', 'DL_Guard', 'You haven''t killed those rats! Go and do your job.','Die Ratten leben noch! Geh jetzt und erledige das.','Du hesch die Ratte nanig killt! Gang ez und mach da.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_StillHere', 'DL_Guard', 'Are you sure you don''t want to help me?','Bist du sicher, dass du mir nicht helfen willst?','Bisch der sicher, dass mer nid helfe willsch?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Yes', 'DL_Guard', 'Yes, totally.','Ja, ganz sicher.','Ja, ganz sicher.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_GoodJob', 'DL_Guard', 'Good job, boy! What do you want as a reward?','Gut gemacht, Junge! Was willst du als Belohnung?','Guet gmacht, Büebli! Wa wetsch als Belohnig?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_GiveMeGold', 'DL_Guard', 'Give me some gold.','Gib mir Gold.','Gib mer Gold.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_GiveMeItem', 'DL_Guard', 'I''d rather have the item.','Ich will lieber etwas anderes.','Ich will lieber öppis anders.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_GivesReward', 'DL_Guard', 'Okay, here you go.','Okay, nimm das.','Okay, nimm das.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Guard_GoAway', 'DL_Guard', 'Go away, I have nothing to do for you anymore.','Geh weg, ich hab nichts mehr für dich zu tun.','Verpiss di, han nüt me ztue für dich.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_SellMeSomething', 'DL_Guard', 'Sell me something.','Verkauf mir was.','Verchauf mer öppis.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_TalkToMe', 'DL_Guard', 'Talk to me.','Sprich mit mir.','Red mit mir.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Trade_TakeALook', 'DL_Guard', 'Take a look, maybe there''s something for you.','Schau sie dir an, vielleicht ist etwas für dich dabei.','Luegs der ah, vilicht findsch was.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Bye', 'DL_Guard', 'Bye','Tschüss','Tschüss');

