INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_Na', 'dl_npc_zeff4', 'I knew you would be successful!', 'Ich wusste, du würdest es schaffen!', 'Ich ha gwüsst, dases schaffsch!');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhoAreYou', 'dl_npc_zeff4', 'Who are you?', 'Wer bist du?', 'Wer bisch du?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_LookingGood', 'dl_npc_zeff4', 'You''re looking good.', 'Du siehst gut aus.', 'Gsesch guet us.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_CurseBroken', 'dl_npc_zeff4', 'The curse is finally broken.', 'Der Fluch wurde endlich gebrochen.', 'De Fluech isch endli broche.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_WhoAreYou', 'dl_npc_zeff4', 'Don''t you recognize me? I''m Zeff. A little less fur, but still Zeff.', 'Erkennst du mich nicht? Ich bin Zeff. Ein bisschen weniger Fell, aber immer noch Zeff.', 'Erkennsch mi denn nid? Ich bi de Zeff. Es bitz weniger Fell, aber immer no de Zeff.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_WhoAreYou2', 'dl_npc_zeff4', 'The curse is finally broken. Thank you, young mage.', 'Der Fluch ist endlich gebrochen. Danke, junger Magier.', 'De Fluech isch endli broche. Danke, junge Magier.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_LookingGood', 'dl_npc_zeff4', 'Yeh, right? A little less fur, but I''m happy to be back.', 'Ja, definitiv. Ein bisschen weniger Fell, aber ich bin froh, bin ich wieder zurück.', 'Jo, gell. Es bitz weniger Fell, aber ich bi froh, dasi wider zrugg bi.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_CurseBroken', 'dl_npc_zeff4', 'It truly is. Thank you, young mage. I''ll never forget you.', 'Das ist wahr. Vielen Dank, junger Magier. Ich werde dich niemals vergessen.', 'Isch so. Danke tusig, junge Magier. Ich wird di nie vergesse.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_Thanks', 'dl_npc_zeff4', 'Thank you!', 'Danke!', 'Danke!');
