INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Morton_BeGone', 'dl_npc_morton', 'What are you doing here? You''re disturbing the peace of the dead. Be gone!', 'Was machst du hier? Du störst die Ruhe der Toten. Hinfort mit dir.', 'Was machsch du do? Du störsch d''Rueh vo dä Tote. Abfaahrä!');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Morton_Necromancers', 'dl_npc_morton', 'Be careful with this magic, boy...', 'Pass auf mit dieser Magie, Junge...', 'Uffbassä mit dere Magie, Bueb...');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_Syrah', 'dl_npc_morton', 'Syrah sent me. I need to go into that crypt.', 'Syrah schickt mich. Ich muss in diese Krypta.', 'D''Syrah het mich gschickt. Ich mun i die Krypta.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_GuysLikeMe', 'dl_npc_morton', 'What do you mean with "guys like me"?', 'Was meinst du mit "Typen wie mich"?', 'Was meinsch mit "Type wie ich"?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_OtherGuy', 'dl_npc_morton', 'She''s sent another guy?', 'Sie hat einen anderen geschickt?', 'Si het en andere gschickt?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Morton_Syrah', 'dl_npc_morton', 'Ah, Syrah. (Morton stares at you) Why does she always hire guys like you. ', 'Ah, Syrah. (Morton starrt dich an) Wieso heuert sie auch immer Typen wie dich für ihre Aufträge an.', 'Ah, d''Syrah. (Dr Morton starrt di aa) Wurumm stellt sie au immer so Type wie dich aa.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Morton_Syrah2', 'dl_npc_morton', '(Sighs) You can go in. But hurry up and don''t touch anything you don''t need.', '(Seufzt) Du kannst rein. Aber beeil dich und fass nichts an, das du nicht brauchst.', '(Seufzt) Chasch iinä. Aber bressier und nüt aadööplä wod nid bruchsch.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Morton_GuysLikeMe', 'dl_npc_morton', 'Green no-goods. The last one she sent to the crypt has never gotten out again.', 'Grünschnäblige Nichtsnutze. Der letzte, den sie hierher geschickt hat, ist nie wieder herausgekommen.', 'Grienschnääbligi Nichtsnütz. Dr letscht, wo sie do ane gschickt het, isch nie me usecho.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Morton_OtherGuy', 'dl_npc_morton', 'Yes, yes. Red hair, seemed to be as old as you and exactly as greenly. But no more chit-chat, I need to work.', 'Ja, ja. Rotes Haar, war etwa so alt wie du und genau so naiv. Aber genug geredet, ich muss jetzt arbeiten.', 'Jo, jo. Roti Hoor, isch öppä so alt gsi wie du und genau so naiv. Aber gnueg gschnuuret, ich mues jetzt schaffe.');
