INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Farmer', 'dl_npc_ivo','Is this your farm?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Merchant', 'dl_npc_ivo','Could you sell me some goods?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Gandria', 'dl_npc_ivo','What can you tell me about Gandria?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Job', 'dl_npc_ivo','What job can you offer?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Sheep', 'dl_npc_ivo','About your sheep...','Wegen deinen Schafen...','Wege dine Schöfli...');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Bye', 'dl_npc_ivo','Bye.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_Farmer', 'dl_npc_ivo','Yes, I''m the farmer here. Are you looking for a job?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_NoJob', 'dl_npc_ivo','No, not really.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_AskSheep', 'dl_npc_ivo','I heard that your sheep are disappearing?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_SheepQuest', 'dl_npc_ivo','Yes, can I do something for you?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_Gandria', 'dl_npc_ivo','Gandria is under the tightly-controlled jurisdiction of the Clerics and their paladins.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_Paladins', 'dl_npc_ivo','Useless mages with shiny armour and that''s about it. They don''t lift a finger for people like us - still, we work for them.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_FightBack', 'dl_npc_ivo','Why don''t you do something about it?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_TalkToThem', 'dl_npc_ivo','I could try and talk to them...','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_YourProblem', 'dl_npc_ivo','Well, that''s your problem.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_FightBack', 'dl_npc_ivo','It wouldn''t be a good idea to rebel against the Clerics. As long as they leave us alone, we''re good.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_TalkToThem', 'dl_npc_ivo','Like we''ve never tried reasoning with them before... No. Talking is no use. Commoners like us are only scum to them.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_MyProblem', 'dl_npc_ivo','I guess it is.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_Merchant', 'dl_npc_ivo','My son Tristan is responsible for selling our goods. Go and talk to him if you want to buy something.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_SheepDisappearing', 'dl_npc_ivo','That''s true, unfortunately.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_SheepQuest', 'dl_npc_ivo','Lately, some of my sheep went missing. Could be a wolf, could be some bandits.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_Grateful', 'dl_npc_ivo','I would be very grateful if you could take care of the thief.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhereStart', 'dl_npc_ivo','Where should I start searching for the thief?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_ZeffIsIt', 'dl_npc_ivo','I know who the thief is...','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_MonsterBanished', 'dl_npc_ivo','The sheep thief won''t bother you anymore.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Back', 'dl_npc_ivo','[BACK]','[ZURÜCK]','[ZRUGG]');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_AskTristan', 'dl_npc_ivo','Hm. You could ask my son, Tristan, he''s in charge of tending the sheep.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Cendric_ZeffIsIt', 'dl_npc_ivo','A wolf-monster named Zeff is responsible for your missing sheep!','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_GoAndKill', 'dl_npc_ivo','Interesting. And now go and make sure that he won''t steal any more sheep. How you do it is for you to decide.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Ivo_ThankYou', 'dl_npc_ivo','Really? The thief won''t come again? Thank you so much for helping us! Go to Tristan and tell him to give you a reward.','','');

