INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhoAreYou', 'dl_npc_thea', 'Who are you?','Wer bist du?','Wer bisch du?', '¿Quién eres?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhatAreYouDoing', 'dl_npc_thea', 'What are you doing here?','Was machst du hier?','Was machsch du da?', '¿Qué estás haciendo aquí?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Mages', 'dl_npc_thea', 'What do you think about mages?','Was hältst du von Magiern?','Was haltisch so vo Magier?', '¿Qué piensas de los magos?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Gandria', 'dl_npc_thea', 'What do you know about the city Gandria?','Was weisst du über die Stadt Gandria?','Was weisch du über d''Stadt Gandria?', '¿Qué sabes de la ciudad de Gandria?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_IAm', 'dl_npc_thea', 'My name is Thea... and you?','Ich heisse Thea... und du?','I heissä Thea... u
du?', 'Me llamo Thea... y ¿tú?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Cendric', 'dl_npc_thea', 'I''m Cendric. Nice to meet you.','Ich bin Cendric. Freut mich.','Ich bi de Cendric. Freut mi.', 'Soy Cendric. Mucho gusto.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_DoesntMatter', 'dl_npc_thea', 'My name isn''t of importance.','Mein Name ist nicht wichtig.','Min Name isch nid wichtig.', 'Mi nombre no es importante.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Nice', 'dl_npc_thea', 'Nice to meet you, too!','Freut mich auch, dich kennenzulernen!','Fröit mi o, di z
lehrä kennä!', '¡Mucho gusto!');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Pity', 'dl_npc_thea', 'Pity, I would have loved to know it.','Schade, ich hätte ihn gerne erfahren.','Schad, hät nä gärn erfahrä.', 'Lástima, me habría encantado saberlo.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_WhatAmIDoing', 'dl_npc_thea', 'I had to deliver some goods from the farmers and then decided to stay for a while.','Ich musste einige Güter von den Bauern hierher bringen und dachte, ich bleib'' doch gleich ein bisschen.','I ha äs paar Sachä vo dä Buurä müässä dahäre bringä u ha däicht, i chönnt ja eifach no chli bliibä.', 'Tenía que entregar unos productos de los granjeros y después decidí quedarme un rato.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_VeryAlone', 'dl_npc_thea', 'You are traveling alone?','Du bist alleine unterwegs?','Du bisch elei unterwägs?', '¿Estás viajando sola?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WorkForFarmers', 'dl_npc_thea', 'Do you work for the farmers?','Arbeitest du für die Bauern?','Schaffsch du für d''Buure?', '¿Trabajas para los granjeros?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_VeryAlone', 'dl_npc_thea', 'Yes, I always travel on my own. But it has become dangerous lately outside of the city walls of Gandria. I''d rather take someone with me in the future.','Ja, ich reise immer alleine. Aber ausserhalb der Stadtmauern von Gandria ist es in letzter Zeit gefährlich geworden. Ich würde lieber jemanden dabei haben in Zukunft.','Ja, i reise immer alleini. Aber usserhaub vo dä Stadtmuurä vo Gandria ischs i letzter Zyt gfährlech wordä. I wür lieber öpper derbii ha i Zuekunft.', 'Sí, siempre viajo sola. Aunque recientemente se ha vuelto peligroso en las afueras de la ciudad de Gandria. Preferiría llevar a alguien conmigo en el futuro.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_WorkForFarmers', 'dl_npc_thea', 'Yes, I''m a maid at Ivo''s farm. But I''d rather find work in the city of Gandria. It''s safe there, at least.','Ja, ich bin eine Magd auf Ivos Bauernhof. Aber ich würde viel lieber in der Stadt Gandria Arbeit finden. Dort ist es wenigstens sicher.','Ja, i bi ä Magd uf em Ivo sim Buurähof. Aber i wür viu lieber ir Stadt Gandria Arbit fingä. Dert ischs wenigschtens sicher.', 'Sí, soy una sirvienta en la granja de Ivo. Aunque preferiría encontrar trabajo en la ciudad de Gandria. Por lo menos ahí es seguro.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhatIsDangerous', 'dl_npc_thea', 'What is dangerous out here, then?','Was ist denn hier draussen gefährlich?','Was isch denn da usse so gföhrlich?', 'Entonces, ¿qué hay de peligroso en las afueras?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Beast', 'dl_npc_thea', 'There is a beast lurking around. It must be pretty hungry, as most of our sheep are gone.','Ein Biest schleicht umher, und es muss ziemlich hungrig sein, denn die meisten unserer Schafe sind weg.','Äs Biischt schliicht umenang u äs isch gloub zimlech hungrig, wü di meischtä vo üsnä Schäfli si wäg.', 'Hay una bestia al acecho y debe estar muy hambrienta, ya que la mayoría de nuestras ovejas ha desaparecido.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Beast2', 'dl_npc_thea', 'Nobody has really seen it, but I swear; I saw a huge shadow disappear into the North last night.','Niemand hat es bisher wirklich zu Gesicht bekommen, aber ich schwöre, ich habe letzte Nacht einen riesigen Schatten in Richtung Norden verschwinden sehen.','Äs hets bis itz no niemer würklech gseh, aber i chönnti schwörä, dass i gester Nacht ä riesigä Schattä i nördlicher Richtig ha gse verschwinde.', 'De momento, nadie ha visto a la criatura en sí, pero te juro que anoche vi una inmensa sombra desaparecer al Norte.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Beast3', 'dl_npc_thea', 'And in the morning, another sheep was missing.','Und am Morgen fehlte uns wieder ein Schaf.','UU am Morgä het üs scho wieder es Schäfli gfäuht.', 'En la mañana, otra oveja había desaparecido.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Mages', 'dl_npc_thea', 'Well, most of them are quite reasonable people. They lead our kingdom, at least.','Nunja, die meisten von ihnen sind ziemlich vernünftig. Immerhin führen sie unser Königreich.','Naja, di meischtä vo ihnä si zimlech vernünftig. Immerhin füährä si üses Chünigriich.','Bueno, la mayoría de ellos es gente razonable. Al menos guían nuestro reino.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Mages2', 'dl_npc_thea', 'And I really think that we owe them a lot - The farmer Ivo told me that in the past, there were even mages that controlled the weather to help farmers like him.','Und ich denke wirklich, dass wir ihnen viel zu verdanken haben - Der Bauer Ivo hat mir gesagt, dass früher die Magier sogar das Wetter kontrolliert haben, um den Bauern zu helfen.','U i däiche w ürklech, dass mer ihnä viu z verdankä hei - der Buur Ivo het mer gseit, dass d Magier früecher sogar z Wätter kontrolliert hei, zum dä Buurä häufe.', 'Y pienso que, en realidad, les debemos mucho. El granjero Ivo me comentó que incluso en el pasado había magos que controlaban el clima para ayudar a granjeros como él.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Gandria', 'dl_npc_thea', 'It''s the capital city of our kingdom. Where the king resides - and all the important people, of course. Ah, I wish I could live there!','Es ist die Hauptstadt unseres Königreichs. Wo der König lebt - und natürlich alle wichtigen Leute. Ach, ich wünschte, ich könnte auch dort wohnen.','Äs isch d Houptstadt vo üsem Chünigriich. Wo der Chünig läbt - u natürlich au diä wichtigä Lüt. Ach, i wünschti, i chönnti o dert wohnä.', 'Es la capital de nuestro reino, donde reside el rey y todas las personas importantes, por supuesto. Ah... ¡Cuánto desearía vivir ahí!');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Syrah', 'dl_npc_thea', 'I found a job for you in Gandria.','Ich habe einen Job für dich in Gandria gefunden.', 'Ich ha en Job für dich in Gandria gfunde.', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Cendric_Syrah', 'dl_npc_thea', 'The alchemist Syrah would take you as an apprentice.','Die Alchemisting Syrah würde dich als Lehrtochter nehmen.', 'D''Alchemistin Syrah wür di als Lehrtochter nä.', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Syrah', 'dl_npc_thea', 'Oh, really? I always wanted to work with herbs and potions. Thank you so much!','Oh, wirklich? Ich wollte schon immer mit Kräutern und Tränken arbeiten. Vielen Dank!', 'Oh, würklech? I ha scho immer mit Chrüttli u Tränk wöuä schaffe. Dankä tusig!', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Syrah2', 'dl_npc_thea', 'I''ll tell Ivo and then travel to Gandria as fast as possible.','Ich werde es Ivo erzählen und dann so schnell wie möglich nach Gandria reisen.', 'I wirdes am Ivo säge u när so schnäu wie müglech nach Gandria reisä.', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Syrah3', 'dl_npc_thea', 'Don''t forget to visit me when I''m there!','Vergiss nicht, mich dann in Gandria zu besuchen!', 'Vergiss nid, mi de z Gandria z bsuächä!', '?');