INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_Stop', 'dl_npc_cityguard1','STOP! The gates of Gandria are closed for strangers!','HALT! Die Tore von Gandria sind geschlossen für Fremde!','HALT! D''Tor vo Gandria sind zue für Fremdi!');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhyGatesClosed', 'dl_npc_cityguard1','Why are the gates closed?','Wieso sind die Tore geschlossen?','Weso sind d''Tor zue?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Stranger', 'dl_npc_cityguard1','Do I look like a stranger to you?','Sehe ich denn aus wie ein Fremder?','Gsehn ich öppe us wenen Fremde?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Zeff', 'dl_npc_cityguard1','Do you know a guy called "Zeff"?','Kennst du jemanden namens "Zeff"?','Kennsch du en Typ wo "Zeff" heisst?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_IDontKnowYou', 'dl_npc_cityguard1','I don''t know you. And we can''t let anyone in the city we don''t know.','Ich kenne dich nicht. Und wir können niemanden in die Stadt lassen, den wir nicht kennen.','Ich kenn dich nid. Und mer chönd niemert id Stadt lah womer nid kenned.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Okay', 'dl_npc_cityguard1','Okay...','Okay...','Okay...');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_AreYouSure', 'dl_npc_cityguard1','Are you entirely sure that you don''t recognize me?','Bist du dir ganz sicher, dass du mich nicht kennst?','Bisch der ganz sicher dassd mich nid kennsch?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_Eyeballing', 'dl_npc_cityguard1','(Eyeballs you) Yes. Maybe I don''t know every filthy vagabond that lurks around at the waterfront, but I would certainly recognize anyone who has left the city in the last few days. And you''re not one of them.','(Mustert dich) Ja. Vielleicht kenne ich nicht jeden dreckigen Herumtreiber, der beim Hafenviertel herumschleicht, aber ich würde sicher jeden erkennen, der die Stadt in den letzten Tagen verlassen hat. Und du bist keiner davon.','(Muschteret dich) Ja. Vilicht kenni nid jede dreckig Strolch, wo sich im Hafeviertel umetriibt, aber ich wür jede erkenne, wo ide letzte Täg d''Stadt verlah het. Und du bisch kene devo.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_PeopleDisappearing', 'dl_npc_cityguard1','There were a few alarming cases of people leaving the city and not returning, lately.','Es gab ein paar beunruhigende Fälle von Bürgern, die die Stadt verlassen haben und noch nicht zurückgekehrt sind.','Es het es paar beunruhigendi Fäll gä vo Lüüt, wo d''Stadt verlah hend und nanig zrugg cho sind.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_GatesClosed', 'dl_npc_cityguard1','We have to assume that there is still something or someone out there that is responsible for this. The gates stay closed until this mystery is solved.','Wir müssen annehmen, dass da draussen immer noch etwas ist, das dafür verantwortlich ist. Die Tore bleiben geschlossen, bis dieses Rätsel gelöst ist.','Mir mönd ane, dass da usse immerna öppis isch, wo dadefür verantwortlich isch. D''Tor bliibed zue, solang das Rätsel nanig glöst isch.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_Zeff', 'dl_npc_cityguard1','Hmm, let me think... Yes, if I recall correctly, there''s a leatherworker Zeff who lives in Gandria. But he''s actually one of the people who are missing. Why do you ask?','Hmm, lass mich nachdenken... Ja, wenn ich mich korrekt erinnere, gibt es einen Lederer namens Zeff in Gandria. Aber er ist einer dieser Personen, die als vermisst gelten. Wieso fragst du?','Hmm, lah mich mal nadenke... Ja, weni mich richtig erinnere, gits en Lederer namens Zeff wo in Gandria lebt. Aber er isch genau eine vo dene Lüüt, wo vermisst werded. Weso frögsch?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Nevermind', 'dl_npc_cityguard1','Nevermind...','Ach, nichts...','Scho guet...');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_IveSeenZeff', 'dl_npc_cityguard1','I''ve seen him! He was turned into a monster!','Ich habe ihn gesehen! Er wurde in ein Monster verwandelt!','Ich hanen gse! Er isch ine Monster verwandlet worde!');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Citguard_Laughs', 'dl_npc_cityguard1','(Laughs) Yes, yes, of course, a monster. And now tell this bullshit someone who actually believes it. Off you go.','(Lacht) Ja, ja, bestimmt, ein Monster. Und jetzt erzähl diesen Unsinn jemandem, der ihn glaubt. Ab mit dir.','(Lachet) Ja, ja, sicher, es Monster. Und jetzt verzell de Seich öpperem, wo ihn glaubt. Verpiss dich jetz besser.');

