INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_WelcomeBack', 'dl_npc_zeff3', 'Ah, it''s you. Welcome to Gandria. A beautiful city, isn''t it.', 'Ah, du bist es. Willkommen in Gandria. Eine schöne Stadt, nicht wahr.', 'Ah, du bisches. Willkomme in Gandria. E schöni Stadt, gell.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_IGotHat', 'dl_npc_zeff3', 'You''re lucky, I''ve just finished the hat I promised you. Thanks again for saving me.', 'Du hast Glück, ich habe den Hut, den ich dir versprochen habe, gerade jetzt fertiggestellt. Danke nochmals, dass du mich gerettet hast.', 'Du hesch Glück, ich ha de Huet, woni dir versproche ha, grad fertig becho. Danke namal dasd mich gretted hesch.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_Trade', 'dl_npc_zeff3', 'What do you have to offer? [TRADE]', 'Was hast du im Angebot? [HANDELN]', 'Was hesch so im Agebot? [HANDLE]');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_Leatherworking', 'dl_npc_zeff3', 'Could you craft something for me?', 'Könntest du mir etwas anfertigen?', 'Chöntsch du mir öppis afertige?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_End', 'dl_npc_zeff3', 'See you later.', 'Bis später.', 'Bis spöter.');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_Leatherworking', 'dl_npc_zeff3', 'Sure, if you got a fur for me?', 'Natürlich, wenn du ein Fell für mich dabei hast?', 'Sicher, wenn du es Fell für mich debii hesch?');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_FireRatFur', 'dl_npc_zeff3', 'Scarf of the Fire Rat', 'Schal der Feuerratte', 'Füürratte Halstuech');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Choice_NothingToCraft', 'dl_npc_zeff3', 'I''ll come back later. [BACK]', 'Ich komme später wieder. [ZURÜCK]', 'Ich chum spöter namal. [ZRUGG]');
INSERT INTO text(text_id, text_type, english, german, swiss_german) values ('DL_Zeff_FireRatFur', 'dl_npc_zeff3', 'The fur of a fire rat, how nice. It has the ability to protect you against fire.', 'Das Fell einer Feuerratte, wie hübsch. Es hat die Eigenschaft, dich vor Feuer zu schützen.', 'Es Fell vonere Füürratte, we hübsch. Es het d''''Eigeschaft, dich vor Füür z''schütze.');
