INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('', 'dl_npc_inina','','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('', 'dl_npc_inina','','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('', 'dl_npc_inina','','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('', 'dl_npc_inina','','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('', 'dl_npc_inina','','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Hey', 'dl_npc_inina','Hey.','Hallo.','Hoi.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Bye', 'dl_npc_inina','','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_Hey', 'dl_npc_inina','Hello, young mage. I''m Inina, High Priestess of the Clerics. How can I help you?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatDoing', 'dl_npc_inina','What are you doing here?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Mage', 'dl_npc_inina','How do you know I''m a mage?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Aura', 'dl_npc_inina','Can you "see" my aura?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Farmers', 'dl_npc_inina','Why do you oppress the farmers? They need your help.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_MissingPeople', 'dl_npc_inina','What do you know about the missing people of Gandria?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_MissingPaladin', 'dl_npc_inina','Maybe I could search for the paladin?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_AboutPaladin', 'dl_npc_inina','About the missing paladin...','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_CanYouTeachMe', 'dl_npc_inina','Can you teach me something?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_WhatDoing', 'dl_npc_inina','Do you see this shrine? Its power is weakened. We''re here to find out why.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Shrine', 'dl_npc_inina','What kind of shrine is this?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_PowerWeakened', 'dl_npc_inina','What could possibly weaken its power?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatDo', 'dl_npc_inina','What did you do until now to find the cause?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_Shrine', 'dl_npc_inina','It''s a shrine for the Eternal Light. Mages and commoners can come here and find strength and peace in prayer.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_PowerWeakened', 'dl_npc_inina','It seems like there is some magic around that is disturbing the divine magic of the shrine. We need to find the cause of this interfering magic.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_WhatDo', 'dl_npc_inina','We''ve sent one of our paladins in the cave behind the shrine, but he has not returned until now.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_MissingPaladin1', 'dl_npc_inina','Yes, maybe you could help us. The name of the paladin I sent into the cave is Marcus.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_MissingPaladin2', 'dl_npc_inina','He has taken my pendant with him. A special pendant that holds some divine energy, it shines in the dark, so you should find him.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_MissingPaladin3', 'dl_npc_inina','You''ll better take something with you that lights your way. I cannot accompany you, as I''m still trying to purify the magic of the shrine.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_Farmers', 'dl_npc_inina','There were some incidents where people left the city and didn''t return. We have to tackle this problem first before we take care of some missing sheep.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_MissingPeople', 'dl_npc_inina','We suppose that these incidents are connected to the strange magical energy we are observing here. But this has yet to be confirmed.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_Mage', 'dl_npc_inina','(Smiles) The Eternal Light is well-disposed towards you. You have a very special aura.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_Aura', 'dl_npc_inina','No, I can only feel it, like most mages do. There are very few mages out there that are able to see auras, the clairvoyant, but I''m not one of them.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhereLight', 'dl_npc_inina','Where can I get a light?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhereSearch', 'dl_npc_inina','Where should I start to search for him?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatsInForMe', 'dl_npc_inina','What''s in for me if I find him?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_FoundPaladin', 'dl_npc_inina','I found the Paladin. He''s dead. [Give the pendant]','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Back', 'dl_npc_inina','[BACK]','[ZURÜCK]','[ZRUGG]');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_WhereLight', 'dl_npc_inina','You''ll need a torch. I don''t have one, but I''m certain that you can buy one at the farm.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_WhereSearch', 'dl_npc_inina','He went westward to a cave.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_WhatsInForMe', 'dl_npc_inina','Well, as you''re a mage, I can teach you the path of the Eternal Light. You''ll never need to use a torch again. (Smiles)','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_FoundPaladin', 'dl_npc_inina','Oh no. That''s terrible. He was a good man. I''m going to pray for him. Thank you for bringing my pendant back.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_FoundPaladin2', 'dl_npc_inina','We really need to find out what''s behind all this.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_LearnLight1', 'dl_npc_inina','Yes, you''ve proven yourself worthy to learn the way of the Eternal Light.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_LearnLight2', 'dl_npc_inina','To create a magical light, you''ll need a weapon that is capable of focusing divine magic. Then, concentrate the divine energy around you and let it shine. ','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Inina_NoTeach', 'dl_npc_inina','We can''t tell yet whether your heart is pure. You have to prove first that you are willing to help us.','','');

