INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhoAreYou', 'dl_npc_thea', 'Who are you?','Wer bist du?','Wer bisch du?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatAreYouDoing', 'dl_npc_thea', 'What are you doing here?','Was machst du hier?','Was machsch du da?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Mages', 'dl_npc_thea', 'What do you think about mages?','Was hältst du von Magiern?','Was haltisch so vo Magier?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Gandria', 'dl_npc_thea', 'What do you know about the city Gandria?','Was weisst du über die Stadt Gandria?','Was weisch du über d''Stadt Gandria?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_IAm', 'dl_npc_thea', 'My name is Thea... and you?','Ich heisse Thea... und du?','Ich heisse Thea... und du?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Cendric', 'dl_npc_thea', 'I''m Cendric. Nice to meet you.','Ich bin Cendric. Freut mich.','Ich bi de Cendric. Freut mi.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_DoesntMatter', 'dl_npc_thea', 'My name isn''t of importance.','Mein Name ist nicht wichtig.','Min Name isch nid wichtig.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_Nice', 'dl_npc_thea', 'Nice to meet you, too!','Freut mich auch, dich kennenzulernen!','Freut mi au, dich z''kennelerne!');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_Pity', 'dl_npc_thea', 'Pity, I would have loved to know it.','Schade, ich hätte ihn gerne erfahren.','Schad, hetten gern erfahre.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_WhatAmIDoing', 'dl_npc_thea', 'I had to deliver some goods from the farmers and then decided to stay for a while.','Ich musste einige Güter von den Bauern hierher bringen und dachte, ich bleib'' doch gleich ein bisschen.','Ich han es paar Sache vode Buure daane bringe möse und ha denkt, ich chönt ja eifach na chli bliibe.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_VeryAlone', 'dl_npc_thea', 'You are traveling alone?','Du bist alleine unterwegs?','Du bisch elei unterwägs?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WorkForFarmers', 'dl_npc_thea', 'Do you work for the farmers?','Arbeitest du für die Bauern?','Schaffsch du für d''Buure?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_VeryAlone', 'dl_npc_thea', 'Yes, I always travel on my own. But it has become dangerous lately outside of the city walls of Gandria. I''d rather take someone with me in the future.','Ja, ich reise immer alleine. Aber ausserhalb der Stadtmauern von Gandria ist es in letzter Zeit gefährlich geworden. Ich würde lieber jemanden dabei haben in Zukunft.','Ja, ich reise immer elei. Aber usserhalb vode Stadtmuure vo Gandria isches i letzter Ziit gföhrlich worde. Ich wür lieber öpper debii ha in Zuekunft.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_WorkForFarmers', 'dl_npc_thea', 'Yes, I''m a maid at Ivo''s farm. But I''d rather find work in the city of Gandria. It''s safe there, at least.','Ja, ich bin eine Magd auf Ivo''s Bauernhof. Aber ich würde viel lieber in der Stadt Gandria Arbeit finden. Dort ist es wenigstens sicher.','Ja, ich bi e Magd uf em Ivo sim Buurehof. Aber ich wür viel lieber ide Stadt Gandria Arbet finde. Dett isches wenigstens sicher.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatIsDangerous', 'dl_npc_thea', 'What is dangerous out here, then?','Was ist denn hier draussen gefährlich?','Was isch denn da usse so gföhrlich?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_Beast', 'dl_npc_thea', 'There is a beast lurking around, and it must be pretty hungry, as most of our sheep are gone. Nobody has really seen it so far but I swear, I''ve seen a huge shadow disappear into the South last night. And in the morning, another sheep was missing.','Ein Biest schleicht umher, und es muss ziemlich hungrig sein, denn die meisten unserer Schafe sind weg. Niemand hat es bisher wirklich zu Gesicht bekommen, aber ich schwöre, ich habe letzte Nacht einen riesigen Schatten in Richtung Süden verschwinden sehen. Und am Morgen fehlte uns wieder ein Schaf.','Es Biescht schliicht umenand und es isch glaub zimli hungrig, well di meiste vo üsne Schöfli sind weg. Es hets bis jetz na niemert würkli gse, aber ich chönt schwöre dasi gest Nacht en riesige Schatte in südlicher Richtig han verschwinde gse. Und am Morge het üs scho wider es Schöfli gfehlt.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_Mages', 'dl_npc_thea', 'Well, most of them are quite reasonable people. They lead our kingdom, at least.','Nunja, die meisten von ihnen sind ziemlich vernünftig. Immerhin führen sie unser Königreich.','Naja, di meiste vo ihne sind zimlich vernünftig. Immerhin führed si üses Königriich.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_Mages2', 'dl_npc_thea', 'And I really think that we owe them much - The farmer Ivo told me that in the past, there were even mages that controlled the weather to help farmers like him.','Und ich denke wirklich, dass wir ihnen viel zu verdanken haben - Der Bauer Ivo hat mir gesagt, dass früher die Magier sogar das Wetter kontrolliert haben, um den Bauern zu helfen.','Und ich denk würkli, dasmer ihne viel z''verdanke hend - De Buur Ivo het mer gseit, dass d''Magier früener sogar es Wätter kontrolliert hend, zum de Buure helfe.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Thea_Gandria', 'dl_npc_thea', 'It''s the capital city of our kingdom. Where the king resides - and all the important people, of course. Ah, I wish I could live there!','Es ist die Hauptstadt unseres Königreichs. Wo der König lebt - und natürlich alle wichtigen Leute. Ach, ich wünschte, ich könnte auch dort wohnen.','Es ischd Hauptstadt vo üsem Königriich. Wo de König lebt - und natürli all di wichtige Lüüt. Ach, ich wünscht, ich chönt au det wohne.');


