INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhoAreYou', 'dl_npc_andrew', 'Who are you?','Wer bist du?','Wer bisch du?', '¿Quién eres?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhatAreYouDoing', 'dl_npc_andrew', 'What are you doing here?','Was machst du hier?','Was machsch du da?','¿Qué estás haciendo aquí?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Mages', 'dl_npc_andrew', 'What do you think about mages?','Was hältst du von Magiern?','Was haltisch so vo Magier?','¿Qué piensas de los magos?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_TheBridgeIsOk', 'dl_npc_andrew', 'The river is frozen, you can go home.','Der Fluss ist gefroren, du kannst nach Hause gehen.','De Fluss isch gfrore, du chasch heiga.','Ya puedes regresar a casa, el río está congelado.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Andrew_IAm', 'dl_npc_andrew', 'I''m Andrew... hic! Nice to meet ya.','Ich bin Andrew... hicks! Shehr erfreut.','Ich bi de Andrew... hicks! Freut mi.','Soy Andrew (¡hip!) Gusto en conocer... te.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Andrew_IAmDrinking', 'dl_npc_andrew', 'Hehe... shilly question... Having some beers, enjoying my time here... I can''t go back anyway.','Hehe, komische Frage... Ich trinke ein paar Bierchen, geniesshe die Seit da... Kann sowieso nicht zurück.','Hehe... dummi Frog... Ich trink esh paar Bierli, gnüssh die Siit da... Cha showiso nid srugg.','jeje... pregunta apsurda (¡hip!) Tomando unasss cervezasss y... (¡hip!) disfrutando mi tiembo acá... (¡hip!) no buedo regresar de todas formassss.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhyCantYouGoBack', 'dl_npc_andrew', 'Why can''t you go back?','Wieso kannst du nicht zurück?','Weso chasch nid zrugg?','¿Por qué no puedes regresar?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_BackToWhere', 'dl_npc_andrew', 'Back to where?','Wohin zurück?','Woane zrugg?','¿Regresar a dónde?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Andrew_BrokenBridge', 'dl_npc_andrew', 'The bridsh is broken, you know. The bridge to the village, where my wife Ingrid lives. But that ...hic!... doeshnt bother me at all.','Die Brücke isht kabutt, weisht du. Die Brücke ins Dorf, wo mein Weib Ingrid lebt. Aber das ..hicks!... shtört mich gar nischt so.','D''Brugg ish futsch, weisch. D''Brugg is Dorf, wo mis Wiib d''Ingrid lebt. Aber das ..hicks!.. shtört mich gar nid so.','Sabesss algo... (¡hip!) El buente está (¡hip!) roto... ese que lleva a la aldea (¡hip!) donde vive... mmm... mi esposa (¡hip!) bero eso no me molesta bara nada.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Andrew_ToVillage', 'dl_npc_andrew', 'To the village... and my wife, Ingrid. The bridsh is broken, you know. But that ...hic!... doeshnt bother me at all.','Zum Dorf, wo mein Weib lebt, Ingrid. Die Brücke isht kabutt, weisht du. Aber das ..hicks!... shtört mich gar nischt so.','Zrugg is Dorf, wo mis Wiib lebt, D''Ingrid. D''Brugg ish futsch, weisch. Aber das ..hicks!.. shtört mich gar nid so.','A la aldea... y mi esbosa Ingrid. El puente está roto, sabesss. Pero eso (¡hip!) no me molesta para nada.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Andrew_IWontGoBack', 'dl_npc_andrew', 'Yeah, really... but itsh summer, that makes no sense. And... to be honest... hic... I really like it here.','Ja, wirklich... aber es ist doch Ssssommer, das macht gar keinen Sinn. Und... um ehrlich zu shein... hicks... mag ich es, hier su sein.','Ja, würkli... aber es isch doch Ssssummer, das macht gar ke Sinn. Und, sssum ehrlich shi... hicks... findish na ganz gmüetlich da.','¡En serio! ... bero es verano (¡hip!) o será invierno... no tiene sentido. Y... para ser honesto (¡hip!) Me gusta mucho aquí.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Andrew_Mages', 'dl_npc_andrew', 'A bunch of freaks, if y''ask me... hic!... I''m pretty glad that none of them livesh in our village.','Ein Haufen Verrückter, wenn du mich fragsht... hicks! Ich bin ziemlich froh darüber, dash keiner davon in unserem Dorf lebt.','En Huufe Gstörti, wend mi grad so frögsch... hicks! Ich bi ja zimli froh drüber, dash keine vo dene i üserem Dorf lebt.','Eh... Un montón de raros, (¡hip!) si... me preguntasss (¡hip!) Me alegra mucho (¡hip!) que ninguno viva... en nuestra aldea.');

