INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhoAreYou', 'dl_npc_thea', 'Who are you?','Wer bist du?','Wer bisch du?', '¿Quién eres?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhatAreYouDoing', 'dl_npc_thea', 'What are you doing here?','Was machst du hier?','Was machsch du da?', '¿Qué estás haciendo aquí?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Mages', 'dl_npc_thea', 'What do you think about mages?','Was hältst du von Magiern?','Was haltisch so vo Magier?', '¿Qué piensas de los magos?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Gandria', 'dl_npc_thea', 'What do you know about the city Gandria?','Was weisst du über die Stadt Gandria?','Was weisch du über d''Stadt Gandria?', '¿Qué sabes de la ciudad de Gandria?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_IAm', 'dl_npc_thea', 'My name is Thea... and you?','Ich heisse Thea... und du?','Ich heisse Thea... und du?', 'Me llamo Thea... y ¿tú?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Cendric', 'dl_npc_thea', 'I''m Cendric. Nice to meet you.','Ich bin Cendric. Freut mich.','Ich bi de Cendric. Freut mi.', 'Soy Cendric. Mucho gusto.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_DoesntMatter', 'dl_npc_thea', 'My name isn''t of importance.','Mein Name ist nicht wichtig.','Min Name isch nid wichtig.', 'Mi nombre no es importante.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Nice', 'dl_npc_thea', 'Nice to meet you, too!','Freut mich auch, dich kennenzulernen!','Freut mi au, dich z''kennelerne!', '¡Mucho gusto!');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Pity', 'dl_npc_thea', 'Pity, I would have loved to know it.','Schade, ich hätte ihn gerne erfahren.','Schad, hetten gern erfahre.', 'Lástima, me habría encantado saberlo.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_WhatAmIDoing', 'dl_npc_thea', 'I had to deliver some goods from the farmers and then decided to stay for a while.','Ich musste einige Güter von den Bauern hierher bringen und dachte, ich bleib'' doch gleich ein bisschen.','Ich han es paar Sache vode Buure daane bringe möse und ha denkt, ich chönt ja eifach na chli bliibe.', 'Tenía que entregar unos productos de los granjeros y después decidí quedarme un rato.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_VeryAlone', 'dl_npc_thea', 'You are traveling alone?','Du bist alleine unterwegs?','Du bisch elei unterwägs?', '¿Estás viajando sola?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WorkForFarmers', 'dl_npc_thea', 'Do you work for the farmers?','Arbeitest du für die Bauern?','Schaffsch du für d''Buure?', '¿Trabajas para los granjeros?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_VeryAlone', 'dl_npc_thea', 'Yes, I always travel on my own. But it has become dangerous lately outside of the city walls of Gandria. I''d rather take someone with me in the future.','Ja, ich reise immer alleine. Aber ausserhalb der Stadtmauern von Gandria ist es in letzter Zeit gefährlich geworden. Ich würde lieber jemanden dabei haben in Zukunft.','Ja, ich reise immer elei. Aber usserhalb vode Stadtmuure vo Gandria isches i letzter Ziit gföhrlich worde. Ich wür lieber öpper debii ha in Zuekunft.', 'Sí, siempre viajo sola. Aunque recientemente se ha vuelto peligroso en las afueras de la ciudad de Gandria. Preferiría llevar a alguien conmigo en el futuro.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_WorkForFarmers', 'dl_npc_thea', 'Yes, I''m a maid at Ivo''s farm. But I''d rather find work in the city of Gandria. It''s safe there, at least.','Ja, ich bin eine Magd auf Ivo''s Bauernhof. Aber ich würde viel lieber in der Stadt Gandria Arbeit finden. Dort ist es wenigstens sicher.','Ja, ich bi e Magd uf em Ivo sim Buurehof. Aber ich wür viel lieber ide Stadt Gandria Arbet finde. Dett isches wenigstens sicher.', 'Sí, soy una sirvienta en la granja de Ivo. Aunque preferiría encontrar trabajo en la ciudad de Gandria. Por lo menos ahí es seguro.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_WhatIsDangerous', 'dl_npc_thea', 'What is dangerous out here, then?','Was ist denn hier draussen gefährlich?','Was isch denn da usse so gföhrlich?', 'Entonces, ¿qué hay de peligroso en las afueras?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Beast', 'dl_npc_thea', 'There is a beast lurking around, and it must be pretty hungry, as most of our sheep are gone.','Ein Biest schleicht umher, und es muss ziemlich hungrig sein, denn die meisten unserer Schafe sind weg.','Es Biescht schliicht umenand und es isch glaub zimli hungrig, well di meiste vo üsne Schöfli sind weg.', 'Hay una bestia al acecho y debe estar muy hambrienta, ya que la mayoría de nuestras ovejas ha desaparecido.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Beast2', 'dl_npc_thea', 'Nobody has really seen it so far but I swear, I''ve seen a huge shadow disappear into the North last night.','Niemand hat es bisher wirklich zu Gesicht bekommen, aber ich schwöre, ich habe letzte Nacht einen riesigen Schatten in Richtung Norden verschwinden sehen.','Es hets bis jetz na niemert würkli gse, aber ich chönt schwöre dasi gest Nacht en riesige Schatte in nördlicher Richtig han verschwinde gse.', 'De momento, nadie ha visto a la criatura en sí, pero te juro que anoche vi una inmensa sombra desaparecer al Norte.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Beast3', 'dl_npc_thea', 'And in the morning, another sheep was missing.','Und am Morgen fehlte uns wieder ein Schaf.','Und am Morge het üs scho wider es Schöfli gfehlt.', 'En la mañana, otra oveja había desaparecido.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Mages', 'dl_npc_thea', 'Well, most of them are quite reasonable people. They lead our kingdom, at least.','Nunja, die meisten von ihnen sind ziemlich vernünftig. Immerhin führen sie unser Königreich.','Naja, di meiste vo ihne sind zimlich vernünftig. Immerhin führed si üses Königriich.','Bueno, la mayoría de ellos es gente razonable. Al menos guían nuestro reino.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Mages2', 'dl_npc_thea', 'And I really think that we owe them much - The farmer Ivo told me that in the past, there were even mages that controlled the weather to help farmers like him.','Und ich denke wirklich, dass wir ihnen viel zu verdanken haben - Der Bauer Ivo hat mir gesagt, dass früher die Magier sogar das Wetter kontrolliert haben, um den Bauern zu helfen.','Und ich denk würkli, dasmer ihne viel z''verdanke hend - De Buur Ivo het mer gseit, dass d''Magier früener sogar es Wätter kontrolliert hend, zum de Buure helfe.', 'Y pienso que, en realidad, les debemos mucho. El granjero Ivo me comentó que incluso en el pasado había magos que controlaban el clima para ayudar a granjeros como él.');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Gandria', 'dl_npc_thea', 'It''s the capital city of our kingdom. Where the king resides - and all the important people, of course. Ah, I wish I could live there!','Es ist die Hauptstadt unseres Königreichs. Wo der König lebt - und natürlich alle wichtigen Leute. Ach, ich wünschte, ich könnte auch dort wohnen.','Es ischd Hauptstadt vo üsem Königriich. Wo de König lebt - und natürli all di wichtige Lüüt. Ach, ich wünscht, ich chönt au det wohne.', 'Es la capital de nuestro reino, donde reside el rey y todas las personas importantes, por supuesto. Ah... ¡Cuánto desearía vivir ahí!');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Choice_Syrah', 'dl_npc_thea', 'I found a job for you in Gandria.','Ich habe einen Job für dich in Gandria gefunden.', 'Ich ha en Job für dich in Gandria gfunde.', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Cendric_Syrah', 'dl_npc_thea', 'The alchemist Syrah would take you as an apprentice.','Die Alchemisting Syrah würde dich als Lehrtochter nehmen.', 'D''Alchemistin Syrah wür di als Lehrtochter nä.', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Syrah', 'dl_npc_thea', 'Oh, really? I always wanted to work with herbs and potions. Thank you so much!','Oh, wirklich? Ich wollte schon immer mit Kräutern und Tränken arbeiten. Vielen Dank!', 'Oh, würkli? Ich ha scho immer mit Chrütli und Tränk wele schaffe. Danke tusig!', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Syrah2', 'dl_npc_thea', 'I''ll tell Ivo and then travel to Gandria as fast as possible.','Ich werde es Ivo erzählen und dann so schnell wie möglich nach Gandria reisen.', 'Ich wirds em Ivo sege und denn so schnell we möglich nach Gandria reise.', '?');
INSERT INTO text (text_id, text_type, english, german, swiss_german, spanish) values ('DL_Thea_Syrah3', 'dl_npc_thea', 'Don''t forget to visit me when I''m there!','Vergiss nicht, mich dann in Gandria zu besuchen!', 'Vergiss nid, mich denn i Gandria z''bsueche!', '?');


