INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhoAreYou', 'dl_npc_zeff','Who are you?','Wer bist du?','Wer bisch du?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatAreYou', 'dl_npc_zeff','What are you?','Was bist du?','Wa bisch du?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhatAreYouDoing', 'dl_npc_zeff','What are you doing here?','Was machst du hier?','Was machsch du da?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Curse', 'dl_npc_zeff','What curse do you talk about?','Von was für einem Fluch sprichst du?','Vo wa fürme Fluech redsch du?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Leatherworking', 'dl_npc_zeff','Could you craft something for me?','Könntest du mir etwas herstellen?','Chöntsch du mir öppis aafertige?');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_CU', 'dl_npc_zeff','See you later.','Bis bald.','Bis bald.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_SittingHere', 'dl_npc_zeff','I''m sitting here at the fire, hoping not to devour anyone before that curse devours myself.','Ich sitze hier am Feuer und hoffe, dass ich niemanden verschlinge bevor dieser Fluch mich verschlingt.','Ich sitz da am Füürli und hoff, dass ich niemert verschling bevor de Fluech mich verschlingt.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_IAmWho', 'dl_npc_zeff','I''m Zeff.','Ich bin Zeff.','Ich bi de Zeff.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_IAmWhat', 'dl_npc_zeff','(Growls quietly) I see, my outer appearance is striking.','(Knurrt leise) Ich sehe, meine äusserliche Erscheinung fällt auf.','Ich gse scho, mini üsserlich Erschiinig fallt grad uf.');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_IAmSuprised', 'dl_npc_zeff','I''m suprised you have the courage to talk to me. Most people I meet flee in terror when they see my face.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_YouLookNice', 'dl_npc_zeff','I don''t think you look terrifying.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_YouLookTerrible', 'dl_npc_zeff','That''s not suprising. You truly look scary.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_IAmNotAfraid', 'dl_npc_zeff','I''m not afraid of you.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_ThankYouLooks', 'dl_npc_zeff','Thank you. You''re the first person to say something nice since I was exiled from Gandria.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_IAmScary', 'dl_npc_zeff','(Hangs his head) Yes I do. That''s what the people of Gandria also thought, when they decided to exile me from the city.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_YouShouldBe', 'dl_npc_zeff','Maybe you should be. The people of Gandria didn''t exile me without any reason from the city.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_WhyExile', 'dl_npc_zeff','Why were you sent into exile?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_Werewolf', 'dl_npc_zeff','Are you a werewolf?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_Werewolf', 'dl_npc_zeff','You''ve never met a werewolf, have you? A werewolf wouldn''t be able to talk to you.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_Exile', 'dl_npc_zeff','They were regarding me as a threat. And I can''t even hold it against them - this curse is a loose cannon.','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_Craft', 'dl_npc_zeff','Sure, if you got a fur for me?','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_FireRatFur', 'dl_npc_zeff','Scarf of the Fire Rat (1 Fur of a Fire Rat)','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Choice_NothingToCraft', 'dl_npc_zeff','I''ll come back later. [Back]','','');
INSERT INTO text (text_id, text_type, english, german, swiss_german) values ('DL_Zeff_FireRatFur', 'dl_npc_zeff','The fur of a fire rat, how nice. It has the ability to protect you against fire.','','');
