name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2019, os: windows-latest, flags: -DCENDRIC_BUILD_DIALOGUE_TOOL=ON }
        - { name: Linux GCC,      os: ubuntu-latest,  flags: -DCENDRIC_BUILD_DIALOGUE_TOOL=OFF }
        - { name: MacOS XCode,    os: macos-latest,   flags: -DCENDRIC_BUILD_DIALOGUE_TOOL=OFF -DCENDRIC_EXTERNAL_DOCUMENT_FOLDER=ON }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Patch SFML on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: curl https://github.com/SFML/SFML/commit/87aaa9e145659d6a8fc193ab8540cf847d4d0def.patch | git apply --directory=ext/sfml

    - name: Configure CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DCMAKE_VERBOSE_MAKEFILE=ON ${{matrix.platform.flags}}

    - name: Build
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/build --config Release --target install --parallel 4